/**
 * Erik Satie   Gymnopedie No.1
 * Composer: Unknown Composer
 * Converted from MusicXML
 */

import type { SheetMusic } from '../../modules/sheetMusic/types'
import {
  NoteDuration,
  TimeSignature,
  KeySignature,
  Clef,
  TechnicalElement,
} from '../../modules/sheetMusic/types'

export const erik_satie_gymnopedie_no_1: SheetMusic = {
  id: 'erik-satie-gymnopedie-no-1',
  title: 'Erik Satie   Gymnopedie No.1',
  composer: 'Unknown Composer',
  instrument: 'PIANO',
  difficulty: 'INTERMEDIATE',
  difficultyLevel: 6,
  durationSeconds: 94,
  timeSignature: TimeSignature.THREE_FOUR,
  keySignature: 'D Major',
  suggestedTempo: 120,
  stylePeriod: 'CLASSICAL',
  tags: ['converted', 'musicxml', 'public-domain'],
  measures: [
    {
      number: 1,
      notes: [
        {
          keys: [],
          duration: 'q',
          time: 0,
        },
        {
          keys: ['b/3'],
          duration: 'h',
          time: 1,
          stem: 'up',
        },
        {
          keys: ['d/4'],
          duration: 'h',
          time: 3,
          stem: 'up',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'up',
        },
        {
          keys: ['g/2'],
          duration: 'h',
          time: 7,
          stem: 'down',
        },
      ],
      keySignature: KeySignature.D_MAJOR,
      timeSignature: TimeSignature.THREE_FOUR,
    },
    {
      number: 2,
      notes: [
        {
          keys: [],
          duration: 'q',
          time: 0,
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 1,
          stem: 'up',
        },
        {
          keys: ['c#/4'],
          duration: 'h',
          time: 3,
          stem: 'up',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 7,
          stem: 'down',
        },
      ],
    },
    {
      number: 3,
      notes: [
        {
          keys: [],
          duration: 'q',
          time: 0,
        },
        {
          keys: ['b/3'],
          duration: 'h',
          time: 1,
          stem: 'up',
        },
        {
          keys: ['d/4'],
          duration: 'h',
          time: 3,
          stem: 'up',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'up',
        },
        {
          keys: ['g/2'],
          duration: 'h',
          time: 7,
          stem: 'down',
        },
      ],
    },
    {
      number: 4,
      notes: [
        {
          keys: [],
          duration: 'q',
          time: 0,
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 1,
          stem: 'up',
        },
        {
          keys: ['c#/4'],
          duration: 'h',
          time: 3,
          stem: 'up',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 7,
          stem: 'up',
        },
      ],
    },
    {
      number: 5,
      notes: [
        {
          keys: [],
          duration: 'q',
          time: 0,
        },
        {
          keys: ['b/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['f#/5'],
          duration: 'q',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['a/5'],
          duration: 'q',
          time: 8,
          stem: 'up',
        },
        {
          keys: ['g/2'],
          duration: 'h',
          time: 9,
          stem: 'down',
        },
      ],
    },
    {
      number: 6,
      notes: [
        {
          keys: [],
          duration: 'q',
          time: 0,
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['c#/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['g/5'],
          duration: 'q',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['f#/5'],
          duration: 'q',
          time: 8,
          stem: 'up',
        },
        {
          keys: ['c#/5'],
          duration: 'q',
          time: 9,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 10,
          stem: 'down',
        },
      ],
    },
    {
      number: 7,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['b/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['b/4'],
          duration: 'q',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['c#/5'],
          duration: 'q',
          time: 8,
          stem: 'up',
        },
        {
          keys: ['d/5'],
          duration: 'q',
          time: 9,
          stem: 'up',
        },
        {
          keys: ['g/2'],
          duration: 'h',
          time: 10,
          stem: 'down',
        },
      ],
    },
    {
      number: 8,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['c#/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['a/4'],
          duration: 'h',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 9,
          stem: 'down',
        },
      ],
    },
    {
      number: 9,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['b/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['g/2'],
          duration: 'h',
          time: 9,
          stem: 'down',
        },
      ],
    },
    {
      number: 10,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['c#/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 9,
          stem: 'down',
        },
      ],
    },
    {
      number: 11,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['b/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['g/2'],
          duration: 'h',
          time: 9,
          stem: 'down',
        },
      ],
    },
    {
      number: 12,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['c#/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 9,
          stem: 'down',
        },
      ],
    },
    {
      number: 13,
      notes: [
        {
          keys: [],
          duration: 'q',
          time: 0,
        },
        {
          keys: ['b/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['f#/5'],
          duration: 'q',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['a/5'],
          duration: 'q',
          time: 8,
          stem: 'up',
        },
        {
          keys: ['g/2'],
          duration: 'h',
          time: 9,
          stem: 'down',
        },
      ],
    },
    {
      number: 14,
      notes: [
        {
          keys: [],
          duration: 'q',
          time: 0,
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['c#/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['g/5'],
          duration: 'q',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['f#/5'],
          duration: 'q',
          time: 8,
          stem: 'up',
        },
        {
          keys: ['c#/5'],
          duration: 'q',
          time: 9,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 10,
          stem: 'down',
        },
      ],
    },
    {
      number: 15,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['b/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['b/4'],
          duration: 'q',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['c#/5'],
          duration: 'q',
          time: 8,
          stem: 'up',
        },
        {
          keys: ['d/5'],
          duration: 'q',
          time: 9,
          stem: 'up',
        },
        {
          keys: ['g/2'],
          duration: 'h',
          time: 10,
          stem: 'down',
        },
      ],
    },
    {
      number: 16,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['c#/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['a/4'],
          duration: 'h',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 9,
          stem: 'down',
        },
      ],
    },
    {
      number: 17,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['c#/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['c#/5'],
          duration: 'h',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['f#/2'],
          duration: 'h',
          time: 9,
          stem: 'down',
        },
      ],
    },
    {
      number: 18,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['b/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['f#/5'],
          duration: 'h',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['b/1'],
          duration: 'h',
          time: 9,
          stem: 'down',
        },
      ],
    },
    {
      number: 19,
      notes: [
        {
          keys: ['e/4'],
          duration: 'h',
          time: 0,
          stem: 'up',
        },
        {
          keys: ['e/2'],
          duration: 'h',
          time: 2,
          stem: 'down',
        },
        {
          keys: [],
          duration: 'q',
          time: 4,
        },
        {
          keys: ['g/3'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: 'h',
          time: 7,
          stem: 'down',
        },
      ],
    },
    {
      number: 20,
      notes: [
        {
          keys: ['e/4'],
          duration: 'h',
          time: 0,
          stem: 'up',
        },
        {
          keys: ['e/2'],
          duration: 'h',
          time: 2,
          stem: 'down',
        },
        {
          keys: [],
          duration: 'q',
          time: 4,
        },
        {
          keys: ['b/3'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: 'h',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['g/4'],
          duration: 'h',
          time: 9,
          stem: 'down',
        },
      ],
    },
    {
      number: 21,
      notes: [
        {
          keys: ['e/4'],
          duration: 'h',
          time: 0,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 2,
          stem: 'down',
        },
        {
          keys: [],
          duration: 'q',
          time: 4,
        },
        {
          keys: ['f/3'],
          duration: 'h',
          time: 5,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: 'h',
          time: 9,
          stem: 'down',
        },
      ],
    },
    {
      number: 22,
      notes: [
        {
          keys: [],
          duration: 'q',
          time: 0,
        },
        {
          keys: ['a/4'],
          duration: 'q',
          time: 1,
          stem: 'up',
        },
        {
          keys: ['b/4'],
          duration: 'q',
          time: 2,
          stem: 'up',
        },
        {
          keys: ['c/5'],
          duration: 'q',
          time: 3,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['a/1'],
          duration: 'h',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['r'],
          duration: 'q',
          time: 6,
          rest: true,
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: 'h',
          time: 9,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['e/4'],
          duration: 'h',
          time: 11,
          stem: 'down',
        },
      ],
    },
    {
      number: 23,
      notes: [
        {
          keys: [],
          duration: 'q',
          time: 0,
        },
        {
          keys: ['e/5'],
          duration: 'q',
          time: 1,
          stem: 'up',
        },
        {
          keys: ['d/5'],
          duration: 'q',
          time: 2,
          stem: 'up',
        },
        {
          keys: ['b/4'],
          duration: 'q',
          time: 3,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['r'],
          duration: 'q',
          time: 6,
          rest: true,
        },
        {
          keys: ['g/3'],
          duration: 'h',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: 'h',
          time: 9,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: 'h',
          time: 11,
          stem: 'down',
        },
      ],
    },
    {
      number: 24,
      notes: [
        {
          keys: [],
          duration: 'q',
          time: 0,
        },
        {
          keys: ['d/5'],
          duration: 'q',
          time: 1,
          stem: 'up',
        },
        {
          keys: ['c/5'],
          duration: 'q',
          time: 2,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['b/4'],
          duration: 'q',
          time: 3,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['r'],
          duration: 'q',
          time: 6,
          rest: true,
        },
        {
          keys: ['d/3'],
          duration: 'h',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: 'h',
          time: 9,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: 'h',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: 'h',
          time: 13,
          stem: 'down',
        },
      ],
    },
    {
      number: 25,
      notes: [
        {
          keys: [],
          duration: 'q',
          time: 0,
        },
        {
          keys: ['d/5'],
          duration: 'h',
          time: 1,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['r'],
          duration: 'q',
          time: 5,
          rest: true,
        },
        {
          keys: ['c/3'],
          duration: 'h',
          time: 6,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['e/3'],
          duration: 'h',
          time: 8,
          stem: 'up',
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 10,
          stem: 'up',
        },
        {
          keys: ['d/4'],
          duration: 'h',
          time: 12,
          stem: 'up',
        },
      ],
    },
    {
      number: 26,
      notes: [
        {
          keys: [],
          duration: 'q',
          time: 0,
        },
        {
          keys: ['d/5'],
          duration: 'h',
          time: 1,
          stem: 'up',
        },
        {
          keys: ['d/5'],
          duration: 'q',
          time: 3,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['r'],
          duration: 'q',
          time: 6,
          rest: true,
        },
        {
          keys: ['c/3'],
          duration: 'h',
          time: 7,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['f#/3'],
          duration: 'h',
          time: 9,
          stem: 'up',
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 11,
          stem: 'up',
        },
        {
          keys: ['d/4'],
          duration: 'h',
          time: 13,
          stem: 'up',
        },
      ],
    },
    {
      number: 27,
      notes: [
        {
          keys: [],
          duration: 'q',
          time: 0,
        },
        {
          keys: ['e/5'],
          duration: 'q',
          time: 1,
          stem: 'up',
        },
        {
          keys: ['f/5'],
          duration: 'q',
          time: 2,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['g/5'],
          duration: 'q',
          time: 3,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['r'],
          duration: 'q',
          time: 6,
          rest: true,
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: 'h',
          time: 9,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['f/4'],
          duration: 'h',
          time: 11,
          stem: 'down',
          accidental: 'natural',
        },
      ],
    },
    {
      number: 28,
      notes: [
        {
          keys: [],
          duration: 'q',
          time: 0,
        },
        {
          keys: ['a/5'],
          duration: 'q',
          time: 1,
          stem: 'up',
        },
        {
          keys: ['c/5'],
          duration: 'q',
          time: 2,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['d/5'],
          duration: 'q',
          time: 3,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['r'],
          duration: 'q',
          time: 6,
          rest: true,
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: 'h',
          time: 9,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['e/4'],
          duration: 'h',
          time: 11,
          stem: 'down',
        },
      ],
    },
    {
      number: 29,
      notes: [
        {
          keys: [],
          duration: 'q',
          time: 0,
        },
        {
          keys: ['e/5'],
          duration: 'q',
          time: 1,
          stem: 'up',
        },
        {
          keys: ['d/5'],
          duration: 'q',
          time: 2,
          stem: 'up',
        },
        {
          keys: ['b/4'],
          duration: 'q',
          time: 3,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['r'],
          duration: 'q',
          time: 6,
          rest: true,
        },
        {
          keys: ['d/3'],
          duration: 'h',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: 'h',
          time: 9,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: 'h',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: 'h',
          time: 13,
          stem: 'down',
        },
      ],
    },
    {
      number: 30,
      notes: [
        {
          keys: [],
          duration: 'q',
          time: 0,
        },
        {
          keys: ['d/5'],
          duration: 'h',
          time: 1,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: [],
          duration: 'q',
          time: 5,
        },
        {
          keys: ['c/3'],
          duration: 'h',
          time: 6,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['e/3'],
          duration: 'h',
          time: 8,
          stem: 'up',
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 10,
          stem: 'up',
        },
        {
          keys: ['d/4'],
          duration: 'h',
          time: 12,
          stem: 'up',
        },
      ],
    },
    {
      number: 31,
      notes: [
        {
          keys: [],
          duration: 'q',
          time: 0,
        },
        {
          keys: ['d/5'],
          duration: 'h',
          time: 1,
          stem: 'up',
        },
        {
          keys: ['d/5'],
          duration: 'q',
          time: 3,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 4,
          stem: 'down',
        },
        {
          keys: [],
          duration: 'q',
          time: 6,
        },
        {
          keys: ['c/3'],
          duration: 'h',
          time: 7,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['f#/3'],
          duration: 'h',
          time: 9,
          stem: 'up',
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 11,
          stem: 'up',
        },
        {
          keys: ['d/4'],
          duration: 'h',
          time: 13,
          stem: 'up',
        },
      ],
    },
    {
      number: 32,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['b/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['g/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['g/5'],
          duration: 'h',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['e/2'],
          duration: 'h',
          time: 9,
          stem: 'down',
        },
      ],
    },
    {
      number: 33,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['c#/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['f#/5'],
          duration: 'h',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['f#/2'],
          duration: 'h',
          time: 9,
          stem: 'down',
        },
      ],
    },
    {
      number: 34,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['b/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['b/4'],
          duration: 'q',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['a/4'],
          duration: 'q',
          time: 8,
          stem: 'up',
        },
        {
          keys: ['b/4'],
          duration: 'q',
          time: 9,
          stem: 'up',
        },
        {
          keys: ['b/1'],
          duration: 'h',
          time: 10,
          stem: 'down',
        },
      ],
    },
    {
      number: 35,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['c#/4'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['a/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['c#/5'],
          duration: 'q',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['d/5'],
          duration: 'q',
          time: 8,
          stem: 'up',
        },
        {
          keys: ['e/5'],
          duration: 'q',
          time: 9,
          stem: 'up',
        },
        {
          keys: ['e/2'],
          duration: 'h',
          time: 10,
          stem: 'down',
        },
      ],
    },
    {
      number: 36,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['c#/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['a/4'],
          duration: 'h',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['c#/5'],
          duration: 'q',
          time: 9,
          stem: 'up',
        },
        {
          keys: ['d/5'],
          duration: 'q',
          time: 10,
          stem: 'up',
        },
        {
          keys: ['e/5'],
          duration: 'q',
          time: 11,
          stem: 'up',
        },
        {
          keys: ['e/2'],
          duration: 'h',
          time: 12,
          stem: 'down',
        },
      ],
    },
    {
      number: 37,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['a/3'],
          duration: 'q',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: 'q',
          time: 2,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: 'q',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: 'q',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['g/4'],
          duration: 'q',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 6,
          stem: 'up',
        },
        {
          keys: ['e/2'],
          duration: 'h',
          time: 8,
          stem: 'down',
        },
        {
          keys: [],
          duration: 'q',
          time: 10,
        },
        {
          keys: ['b/2'],
          duration: 'q',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: 'q',
          time: 12,
          stem: 'down',
        },
      ],
    },
    {
      number: 38,
      notes: [
        {
          keys: ['c/4'],
          duration: 'h',
          time: 0,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['e/4'],
          duration: 'h',
          time: 2,
          stem: 'up',
        },
        {
          keys: ['a/4'],
          duration: 'h',
          time: 4,
          stem: 'up',
        },
        {
          keys: ['c/5'],
          duration: 'h',
          time: 6,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['a/2'],
          duration: 'h',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: 'h',
          time: 10,
          stem: 'down',
        },
      ],
    },
    {
      number: 39,
      notes: [
        {
          keys: ['d/4'],
          duration: 'h',
          time: 0,
          stem: 'up',
        },
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 2,
          stem: 'up',
        },
        {
          keys: ['a/4'],
          duration: 'h',
          time: 4,
          stem: 'up',
        },
        {
          keys: ['d/5'],
          duration: 'h',
          time: 6,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['a/2'],
          duration: 'h',
          time: 10,
          stem: 'down',
        },
        {
          keys: ['d/3'],
          duration: 'h',
          time: 12,
          stem: 'down',
        },
      ],
    },
    {
      number: 40,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['b/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['g/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['g/5'],
          duration: 'h',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['e/2'],
          duration: 'h',
          time: 9,
          stem: 'down',
        },
      ],
    },
    {
      number: 41,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['a/4'],
          duration: 'h',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['f/5'],
          duration: 'h',
          time: 9,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['e/2'],
          duration: 'h',
          time: 11,
          stem: 'down',
        },
      ],
    },
    {
      number: 42,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['f/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['b/4'],
          duration: 'q',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['c/5'],
          duration: 'q',
          time: 8,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['f/5'],
          duration: 'q',
          time: 9,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['e/2'],
          duration: 'h',
          time: 10,
          stem: 'down',
        },
      ],
    },
    {
      number: 43,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['c/4'],
          duration: 'h',
          time: 1,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['e/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['a/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['e/5'],
          duration: 'q',
          time: 7,
          stem: 'up',
        },
        {
          keys: ['d/5'],
          duration: 'q',
          time: 8,
          stem: 'up',
        },
        {
          keys: ['c/5'],
          duration: 'q',
          time: 9,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['e/2'],
          duration: 'h',
          time: 10,
          stem: 'down',
        },
      ],
    },
    {
      number: 44,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['a/3'],
          duration: 'h',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: 'h',
          time: 3,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['f/4'],
          duration: 'h',
          time: 5,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['a/4'],
          duration: 'h',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['e/5'],
          duration: 'q',
          time: 9,
          stem: 'up',
        },
        {
          keys: ['d/5'],
          duration: 'q',
          time: 10,
          stem: 'up',
        },
        {
          keys: ['c/5'],
          duration: 'q',
          time: 11,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['e/2'],
          duration: 'h',
          time: 12,
          stem: 'down',
        },
      ],
    },
    {
      number: 45,
      notes: [
        {
          keys: ['r'],
          duration: 'q',
          time: 0,
          rest: true,
        },
        {
          keys: ['a/3'],
          duration: 'q',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: 'q',
          time: 2,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: 'q',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: 'q',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['g/4'],
          duration: 'q',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['f/4'],
          duration: 'h',
          time: 6,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['e/2'],
          duration: 'h',
          time: 8,
          stem: 'down',
        },
        {
          keys: [],
          duration: 'q',
          time: 10,
        },
        {
          keys: ['b/2'],
          duration: 'q',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: 'q',
          time: 12,
          stem: 'down',
        },
      ],
    },
    {
      number: 46,
      notes: [
        {
          keys: ['c/4'],
          duration: 'h',
          time: 0,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['e/4'],
          duration: 'h',
          time: 2,
          stem: 'up',
        },
        {
          keys: ['a/4'],
          duration: 'h',
          time: 4,
          stem: 'up',
        },
        {
          keys: ['c/5'],
          duration: 'h',
          time: 6,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['a/2'],
          duration: 'h',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: 'h',
          time: 10,
          stem: 'down',
        },
      ],
    },
    {
      number: 47,
      notes: [
        {
          keys: ['d/4'],
          duration: 'h',
          time: 0,
          stem: 'up',
        },
        {
          keys: ['f/4'],
          duration: 'h',
          time: 2,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['a/4'],
          duration: 'h',
          time: 4,
          stem: 'up',
        },
        {
          keys: ['d/5'],
          duration: 'h',
          time: 6,
          stem: 'up',
        },
        {
          keys: ['d/2'],
          duration: 'h',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['a/2'],
          duration: 'h',
          time: 10,
          stem: 'down',
        },
        {
          keys: ['d/3'],
          duration: 'h',
          time: 12,
          stem: 'down',
        },
      ],
    },
  ],
  metadata: {
    source: 'MusicXML Conversion',
    license: 'Public Domain',
  },
}
