/**
 * Prlude Opus 28 No. 4 In E Minor  Chopin
 * Composer: Fréderic François Chopin(1810–1849)
 * Converted from MusicXML
 */

import type { SheetMusic } from '../../modules/sheetMusic/types'
import {
  NoteDuration,
  TimeSignature,
  KeySignature,
  Clef,
  TechnicalElement,
} from '../../modules/sheetMusic/types'

export const prlude_opus_28_no_4_in_e_minor_chopin: SheetMusic = {
  id: 'prlude-opus-28-no-4-in-e-minor-chopin',
  title: 'Prlude Opus 28 No. 4 In E Minor  Chopin',
  composer: 'Fréderic François Chopin(1810–1849)',
  instrument: 'PIANO',
  difficulty: 'ADVANCED',
  difficultyLevel: 10,
  durationSeconds: 52,
  timeSignature: TimeSignature.FOUR_FOUR,
  keySignature: 'G Major',
  suggestedTempo: 120,
  stylePeriod: 'ROMANTIC',
  tags: ['converted', 'musicxml', 'public-domain'],
  measures: [
    {
      number: 1,
      notes: [
        {
          keys: ['b/3'],
          duration: '8',
          time: 0,
          stem: 'up',
        },
        {
          keys: ['b/4'],
          duration: '16',
          time: 0.5,
          stem: 'up',
        },
        {
          keys: [],
          duration: 'q',
          time: 0.75,
        },
      ],
      keySignature: KeySignature.G_MAJOR,
      timeSignature: TimeSignature.FOUR_FOUR,
    },
    {
      number: 2,
      notes: [
        {
          keys: ['b/4'],
          duration: 'h',
          time: 0,
          stem: 'down',
        },
        {
          keys: ['c/5'],
          duration: 'q',
          time: 2,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 3.5,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 4.5,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 5.5,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 6,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 6.5,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 7.5,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 8.5,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 9,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 9.5,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 10,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 10.5,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 11.5,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 12,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 12.5,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 13,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 13.5,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 14,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 14.5,
          stem: 'down',
        },
      ],
    },
    {
      number: 3,
      notes: [
        {
          keys: ['b/4'],
          duration: 'h',
          time: 0,
          stem: 'down',
        },
        {
          keys: ['c/5'],
          duration: 'q',
          time: 2,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 3.5,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 4.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 5.5,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 6,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 6.5,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 7.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 8.5,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 9,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 9.5,
          stem: 'down',
        },
        {
          keys: ['eb/4'],
          duration: '8',
          time: 10,
          stem: 'down',
          accidental: 'flat',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 10.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['eb/4'],
          duration: '8',
          time: 11.5,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 12,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 12.5,
          stem: 'down',
        },
        {
          keys: ['eb/4'],
          duration: '8',
          time: 13,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 13.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 14,
          stem: 'down',
        },
        {
          keys: ['eb/4'],
          duration: '8',
          time: 14.5,
          stem: 'down',
        },
      ],
    },
    {
      number: 4,
      notes: [
        {
          keys: ['b/4'],
          duration: 'h',
          time: 0,
          stem: 'down',
        },
        {
          keys: ['c/5'],
          duration: 'q',
          time: 2,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 3,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 3.5,
          stem: 'down',
        },
        {
          keys: ['eb/4'],
          duration: '8',
          time: 4,
          stem: 'down',
          accidental: 'flat',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 4.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['eb/4'],
          duration: '8',
          time: 5.5,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 6,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 6.5,
          stem: 'down',
        },
        {
          keys: ['eb/4'],
          duration: '8',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 7.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['eb/4'],
          duration: '8',
          time: 8.5,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 9,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 9.5,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: '8',
          time: 10,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 10.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: '8',
          time: 11.5,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 12,
          stem: 'down',
        },
        {
          keys: ['g#/3'],
          duration: '8',
          time: 12.5,
          stem: 'down',
          accidental: 'sharp',
        },
        {
          keys: ['d/4'],
          duration: '8',
          time: 13,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 13.5,
          stem: 'down',
        },
        {
          keys: ['g#/3'],
          duration: '8',
          time: 14,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: '8',
          time: 14.5,
          stem: 'down',
        },
      ],
    },
    {
      number: 5,
      notes: [
        {
          keys: ['b/4'],
          duration: 'h',
          time: 0,
          stem: 'down',
        },
        {
          keys: ['bb/4'],
          duration: 'q',
          time: 2,
          stem: 'down',
          accidental: 'flat',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['g#/3'],
          duration: '8',
          time: 3.5,
          stem: 'down',
          accidental: 'sharp',
        },
        {
          keys: ['d/4'],
          duration: '8',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 4.5,
          stem: 'down',
        },
        {
          keys: ['g#/3'],
          duration: '8',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: '8',
          time: 5.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 6,
          stem: 'down',
        },
        {
          keys: ['g#/3'],
          duration: '8',
          time: 6.5,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: '8',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 7.5,
          stem: 'down',
        },
        {
          keys: ['g#/3'],
          duration: '8',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: '8',
          time: 8.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 9,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 9.5,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['d/4'],
          duration: '8',
          time: 10,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 10.5,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: '8',
          time: 11.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 12,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 12.5,
          stem: 'down',
        },
        {
          keys: ['c#/4'],
          duration: '8',
          time: 13,
          stem: 'down',
          accidental: 'sharp',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 13.5,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 14,
          stem: 'down',
        },
        {
          keys: ['c#/4'],
          duration: '8',
          time: 14.5,
          stem: 'down',
        },
      ],
    },
    {
      number: 6,
      notes: [
        {
          keys: ['a/4'],
          duration: 'h',
          time: 0,
          stem: 'up',
        },
        {
          keys: ['b/4'],
          duration: 'q',
          time: 2,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 3.5,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 4,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 4.5,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 5.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 6,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 6.5,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 7.5,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 8.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 9,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 9.5,
          stem: 'down',
          accidental: 'sharp',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 10,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 10.5,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 11.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 12,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 12.5,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 13,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 13.5,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 14,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 14.5,
          stem: 'down',
        },
      ],
    },
    {
      number: 7,
      notes: [
        {
          keys: ['a/4'],
          duration: 'h',
          time: 0,
          stem: 'up',
        },
        {
          keys: ['b/4'],
          duration: 'q',
          time: 2,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 3.5,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 4.5,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 5.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 6,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 6.5,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 7.5,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 8.5,
          stem: 'down',
        },
        {
          keys: ['d#/3'],
          duration: '8',
          time: 9,
          stem: 'down',
          accidental: 'sharp',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 9.5,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 10,
          stem: 'down',
        },
        {
          keys: ['d#/3'],
          duration: '8',
          time: 10.5,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 11.5,
          stem: 'down',
        },
        {
          keys: ['d#/3'],
          duration: '8',
          time: 12,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 12.5,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 13,
          stem: 'down',
        },
        {
          keys: ['d#/3'],
          duration: '8',
          time: 13.5,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 14,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 14.5,
          stem: 'down',
        },
      ],
    },
    {
      number: 8,
      notes: [
        {
          keys: ['a/4'],
          duration: 'h',
          time: 0,
          stem: 'up',
        },
        {
          keys: ['b/4'],
          duration: '8',
          time: 2,
          stem: 'up',
        },
        {
          keys: ['a/4'],
          duration: '16',
          time: 2.5,
          stem: 'up',
        },
        {
          keys: ['d/3'],
          duration: '8',
          time: 2.75,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 3.25,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 3.75,
          stem: 'down',
        },
        {
          keys: ['d/3'],
          duration: '8',
          time: 4.25,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 4.75,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 5.25,
          stem: 'down',
        },
        {
          keys: ['d/3'],
          duration: '8',
          time: 5.75,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 6.25,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 6.75,
          stem: 'down',
        },
        {
          keys: ['d/3'],
          duration: '8',
          time: 7.25,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 7.75,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 8.25,
          stem: 'down',
        },
        {
          keys: ['d/3'],
          duration: '8',
          time: 8.75,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 9.25,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 9.75,
          stem: 'down',
        },
        {
          keys: ['d/3'],
          duration: '8',
          time: 10.25,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 10.75,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 11.25,
          stem: 'down',
        },
        {
          keys: ['d/3'],
          duration: '8',
          time: 11.75,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 12.25,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 12.75,
          stem: 'down',
        },
        {
          keys: ['d/3'],
          duration: '8',
          time: 13.25,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 13.75,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 14.25,
          stem: 'down',
        },
      ],
    },
    {
      number: 9,
      notes: [
        {
          keys: ['a/4'],
          duration: 'h',
          time: 0,
          stem: 'up',
        },
        {
          keys: ['g#/4'],
          duration: 'q',
          time: 2,
          stem: 'up',
          accidental: 'sharp',
        },
        {
          keys: ['d/3'],
          duration: '8',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 3.5,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['d/3'],
          duration: '8',
          time: 4.5,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 5.5,
          stem: 'down',
        },
        {
          keys: ['d/3'],
          duration: '8',
          time: 6,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 6.5,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['d/3'],
          duration: '8',
          time: 7.5,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 8.5,
          stem: 'down',
        },
        {
          keys: ['d/3'],
          duration: '8',
          time: 9,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 9.5,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 10,
          stem: 'down',
        },
        {
          keys: ['d/3'],
          duration: '8',
          time: 10.5,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 11.5,
          stem: 'down',
        },
        {
          keys: ['d/3'],
          duration: '8',
          time: 12,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 12.5,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 13,
          stem: 'down',
        },
        {
          keys: ['d/3'],
          duration: '8',
          time: 13.5,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 14,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 14.5,
          stem: 'down',
        },
      ],
    },
    {
      number: 10,
      notes: [
        {
          keys: ['g#/4'],
          duration: 'q',
          time: 0,
          stem: 'up',
        },
        {
          keys: ['a/4'],
          duration: '8',
          time: 1,
          stem: 'up',
        },
        {
          keys: ['b/4'],
          duration: '8',
          time: 1.5,
          stem: 'up',
        },
        {
          keys: ['d/5'],
          duration: '8',
          time: 2,
          stem: 'up',
        },
        {
          keys: ['c/5'],
          duration: '8',
          time: 2.5,
          stem: 'up',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 3,
          stem: 'up',
        },
        {
          keys: ['a/4'],
          duration: '8',
          time: 3.5,
          stem: 'up',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 4.5,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 5.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 6,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 6.5,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 7.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 8.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 9,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 9.5,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 10,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 10.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 11.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 12,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 12.5,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 13,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 13.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 14,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 14.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 15,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 15.5,
          stem: 'down',
        },
      ],
    },
    {
      number: 11,
      notes: [
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 0,
          stem: 'up',
        },
        {
          keys: ['a/4'],
          duration: 'q',
          time: 2,
          stem: 'up',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 3.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 4.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 5.5,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 6,
          stem: 'down',
        },
        {
          keys: ['d#/3'],
          duration: '8',
          time: 6.5,
          stem: 'down',
          accidental: 'sharp',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 7.5,
          stem: 'down',
        },
        {
          keys: ['d#/3'],
          duration: '8',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 8.5,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 9,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 9.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 10,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 10.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 11.5,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 12,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 12.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 13,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 13.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 14,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 14.5,
          stem: 'down',
        },
      ],
    },
    {
      number: 12,
      notes: [
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 0,
          stem: 'up',
        },
        {
          keys: ['b/4'],
          duration: '8',
          time: 2,
          stem: 'up',
        },
        {
          keys: ['a/4'],
          duration: 'q',
          time: 2.5,
          stem: 'up',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 3.5,
          stem: 'down',
        },
        {
          keys: ['d#/3'],
          duration: '8',
          time: 4,
          stem: 'down',
          accidental: 'sharp',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 4.5,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['d#/3'],
          duration: '8',
          time: 5.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 6,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 6.5,
          stem: 'down',
        },
        {
          keys: ['d#/3'],
          duration: '8',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 7.5,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['d#/3'],
          duration: '8',
          time: 8.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 9,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 9.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 10,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 10.5,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 11.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 12,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 12.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 13,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 13.5,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 14,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 14.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 15,
          stem: 'down',
        },
      ],
    },
    {
      number: 13,
      notes: [
        {
          keys: ['g/4'],
          duration: '8',
          time: 0,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['f#/4'],
          duration: '8',
          time: 0.5,
          stem: 'up',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 1,
          stem: 'up',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 1.5,
          stem: 'up',
        },
        {
          keys: ['d#/4'],
          duration: '8',
          time: 2,
          stem: 'up',
          accidental: 'sharp',
        },
        {
          keys: ['f#/4'],
          duration: '8',
          time: 2.5,
          stem: 'up',
        },
        {
          keys: ['d/5'],
          duration: '8',
          time: 3,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['c/5'],
          duration: '8',
          time: 3.5,
          stem: 'up',
        },
        {
          keys: ['b/4'],
          duration: '8',
          time: 4,
          stem: 'up',
        },
        {
          keys: ['b/2'],
          duration: 'q',
          time: 4.5,
          stem: 'down',
        },
        {
          keys: ['d#/3'],
          duration: 'q',
          time: 5.5,
          stem: 'down',
          accidental: 'sharp',
        },
        {
          keys: ['a/3'],
          duration: 'q',
          time: 6.5,
          stem: 'down',
        },
        {
          keys: [],
          duration: 'q',
          time: 7.5,
        },
        {
          keys: [],
          duration: 'h',
          time: 8.5,
        },
      ],
    },
    {
      number: 14,
      notes: [
        {
          keys: ['b/4'],
          duration: 'h',
          time: 0,
          stem: 'down',
        },
        {
          keys: ['c/5'],
          duration: 'q',
          time: 2,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 3.5,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 4.5,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 5.5,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 6,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 6.5,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 7.5,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 8.5,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 9,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 9.5,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 10,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 10.5,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 11.5,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 12,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 12.5,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 13,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 13.5,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 14,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 14.5,
          stem: 'down',
        },
      ],
    },
    {
      number: 15,
      notes: [
        {
          keys: ['b/4'],
          duration: 'h',
          time: 0,
          stem: 'down',
        },
        {
          keys: ['c/5'],
          duration: 'q',
          time: 2,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 3.5,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 4.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 5.5,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 6,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 6.5,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 7.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 8.5,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 9,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 9.5,
          stem: 'down',
        },
        {
          keys: ['eb/4'],
          duration: '8',
          time: 10,
          stem: 'down',
          accidental: 'flat',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 10.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['eb/4'],
          duration: '8',
          time: 11.5,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 12,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 12.5,
          stem: 'down',
        },
        {
          keys: ['eb/4'],
          duration: '8',
          time: 13,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 13.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 14,
          stem: 'down',
        },
        {
          keys: ['eb/4'],
          duration: '8',
          time: 14.5,
          stem: 'down',
        },
      ],
    },
    {
      number: 16,
      notes: [
        {
          keys: ['b/4'],
          duration: 'h',
          time: 0,
          stem: 'down',
        },
        {
          keys: ['c/5'],
          duration: 'q',
          time: 2,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 3,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['ab/3'],
          duration: '8',
          time: 3.5,
          stem: 'down',
          accidental: 'flat',
        },
        {
          keys: ['eb/4'],
          duration: '8',
          time: 4,
          stem: 'down',
          accidental: 'flat',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 4.5,
          stem: 'down',
        },
        {
          keys: ['ab/3'],
          duration: '8',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['eb/4'],
          duration: '8',
          time: 5.5,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 6,
          stem: 'down',
        },
        {
          keys: ['ab/3'],
          duration: '8',
          time: 6.5,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: '8',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['f/3'],
          duration: '8',
          time: 7.5,
          stem: 'down',
        },
        {
          keys: ['ab/3'],
          duration: '8',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: '8',
          time: 8.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 9,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['g#/3'],
          duration: '8',
          time: 9.5,
          stem: 'down',
          accidental: 'sharp',
        },
        {
          keys: ['d/4'],
          duration: '8',
          time: 10,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 10.5,
          stem: 'down',
        },
        {
          keys: ['g#/3'],
          duration: '8',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: '8',
          time: 11.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 12,
          stem: 'down',
        },
        {
          keys: ['g#/3'],
          duration: '8',
          time: 12.5,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: '8',
          time: 13,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 13.5,
          stem: 'down',
        },
        {
          keys: ['g#/3'],
          duration: '8',
          time: 14,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: '8',
          time: 14.5,
          stem: 'down',
        },
      ],
    },
    {
      number: 17,
      notes: [
        {
          keys: ['b/4'],
          duration: '8',
          time: 0,
          stem: 'up',
        },
        {
          keys: ['a#/4'],
          duration: '16',
          time: 0.5,
          stem: 'up',
          accidental: 'sharp',
        },
        {
          keys: ['a#/4'],
          duration: 'q',
          time: 0.75,
          stem: 'up',
        },
        {
          keys: ['g/5'],
          duration: 'q',
          time: 1.75,
          stem: 'down',
        },
        {
          keys: ['f#/5'],
          duration: '8',
          time: 2.75,
          stem: 'down',
        },
        {
          keys: ['e/5'],
          duration: '16',
          time: 3.25,
          stem: 'down',
        },
        {
          keys: ['b/4'],
          duration: 'q',
          time: 3.5,
          stem: 'auto',
        },
        {
          keys: ['a#/4'],
          duration: 'q',
          time: 4.5,
          stem: 'auto',
        },
        {
          keys: ['g#/4'],
          duration: 'q',
          time: 5.5,
          stem: 'auto',
          accidental: 'double-sharp',
        },
        {
          keys: ['a#/4'],
          duration: 'q',
          time: 6.5,
          stem: 'auto',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 7.5,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 8,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['d/4'],
          duration: '8',
          time: 8.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 9,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 9.5,
          stem: 'down',
        },
        {
          keys: ['d/4'],
          duration: '8',
          time: 10,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 10.5,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['c#/4'],
          duration: '8',
          time: 11.5,
          stem: 'down',
          accidental: 'sharp',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 12,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 12.5,
          stem: 'down',
        },
        {
          keys: ['c#/4'],
          duration: '8',
          time: 13,
          stem: 'down',
        },
        {
          keys: ['c#/3'],
          duration: '8',
          time: 13.5,
          stem: 'down',
          accidental: 'sharp',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 14,
          stem: 'down',
        },
        {
          keys: ['a#/3'],
          duration: '8',
          time: 14.5,
          stem: 'down',
          accidental: 'sharp',
        },
        {
          keys: ['c#/3'],
          duration: '8',
          time: 15,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 15.5,
          stem: 'down',
        },
        {
          keys: ['a#/3'],
          duration: '8',
          time: 16,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 16.5,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 17,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 17.5,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 18,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 18.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 19,
          stem: 'down',
        },
      ],
    },
    {
      number: 18,
      notes: [
        {
          keys: ['e/5'],
          duration: '8',
          time: 0,
          stem: 'down',
        },
        {
          keys: ['d#/5'],
          duration: '8',
          time: 0.5,
          stem: 'down',
          accidental: 'sharp',
        },
        {
          keys: ['c/6'],
          duration: '8',
          time: 1,
          stem: 'down',
        },
        {
          keys: ['d#/5'],
          duration: '8',
          time: 1.5,
          stem: 'down',
        },
        {
          keys: ['d#/5'],
          duration: '8',
          time: 2,
          stem: 'down',
        },
        {
          keys: ['e/5'],
          duration: '8',
          time: 2.5,
          stem: 'down',
        },
        {
          keys: ['g/5'],
          duration: '8',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['b/4'],
          duration: '8',
          time: 3.5,
          stem: 'down',
        },
        {
          keys: ['b/1'],
          duration: '8',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 4.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 5.5,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: '8',
          time: 6,
          stem: 'down',
        },
        {
          keys: ['a/4'],
          duration: '8',
          time: 6.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 7.5,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: '8',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['a/4'],
          duration: '8',
          time: 8.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 9,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 9.5,
          stem: 'down',
        },
        {
          keys: ['f#/4'],
          duration: '8',
          time: 10,
          stem: 'down',
        },
        {
          keys: ['a/4'],
          duration: '8',
          time: 10.5,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 11.5,
          stem: 'down',
        },
        {
          keys: ['d#/4'],
          duration: '8',
          time: 12,
          stem: 'down',
          accidental: 'sharp',
        },
        {
          keys: ['f#/4'],
          duration: '8',
          time: 12.5,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 13,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 13.5,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 14,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 14.5,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 15,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 15.5,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 16,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 16.5,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 17,
          stem: 'down',
        },
      ],
    },
    {
      number: 19,
      notes: [
        {
          keys: ['d/5'],
          duration: '8',
          time: 0,
          stem: 'up',
          accidental: 'natural',
        },
        {
          keys: ['c/5'],
          duration: '8',
          time: 0.5,
          stem: 'up',
        },
        {
          keys: ['e/5'],
          duration: '8',
          time: 1,
          stem: 'up',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 1.5,
          stem: 'up',
        },
        {
          keys: ['a/4'],
          duration: '8',
          time: 2,
          stem: 'up',
        },
        {
          keys: ['f#/4'],
          duration: 'q',
          time: 2.5,
          stem: 'up',
        },
        {
          keys: ['a/4'],
          duration: '8',
          time: 3.5,
          stem: 'up',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 4.5,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 5.5,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 6,
          stem: 'down',
        },
        {
          keys: ['e/4'],
          duration: '8',
          time: 6.5,
          stem: 'down',
        },
        {
          keys: ['a/2'],
          duration: '8',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 7.5,
          stem: 'down',
        },
        {
          keys: ['f#/3'],
          duration: '8',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['c/4'],
          duration: '8',
          time: 8.5,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 9,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 9.5,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 10,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 10.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 11.5,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 12,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 12.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 13,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 13.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 14,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 14.5,
          stem: 'down',
        },
      ],
    },
    {
      number: 20,
      notes: [
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 0,
          stem: 'up',
        },
        {
          keys: ['b/4'],
          duration: '8',
          time: 2,
          stem: 'up',
        },
        {
          keys: ['a/4'],
          duration: 'q',
          time: 2.5,
          stem: 'up',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 3.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 4.5,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 5.5,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 6,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 6.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 7.5,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 8.5,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 9,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 9.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 10,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 10.5,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 11.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 12,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 12.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 13,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 13.5,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 14,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 14.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 15,
          stem: 'down',
        },
      ],
    },
    {
      number: 21,
      notes: [
        {
          keys: ['f#/4'],
          duration: 'h',
          time: 0,
          stem: 'up',
        },
        {
          keys: ['f#/4'],
          duration: '8',
          time: 2,
          stem: 'up',
        },
        {
          keys: ['e/4'],
          duration: '16',
          time: 2.5,
          stem: 'up',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 2.75,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 3.25,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 3.75,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 4.25,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 4.75,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 5.25,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 5.75,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 6.25,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 6.75,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 7.25,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 7.75,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 8.25,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 8.75,
          stem: 'down',
        },
        {
          keys: ['d#/3'],
          duration: '8',
          time: 9.25,
          stem: 'down',
          accidental: 'sharp',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 9.75,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 10.25,
          stem: 'down',
        },
        {
          keys: ['d#/3'],
          duration: '8',
          time: 10.75,
          stem: 'down',
        },
        {
          keys: ['b/3'],
          duration: '8',
          time: 11.25,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 11.75,
          stem: 'down',
        },
        {
          keys: ['d#/3'],
          duration: '8',
          time: 12.25,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 12.75,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 13.25,
          stem: 'down',
        },
        {
          keys: ['d#/3'],
          duration: '8',
          time: 13.75,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 14.25,
          stem: 'down',
        },
      ],
    },
    {
      number: 22,
      notes: [
        {
          keys: ['e/4'],
          duration: 'h',
          time: 0,
          stem: 'up',
        },
        {
          keys: ['f#/4'],
          duration: 'q',
          time: 2,
          stem: 'up',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 3.5,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 4.5,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 5.5,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 6,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 6.5,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 7,
          stem: 'down',
        },
        {
          keys: ['bb/3'],
          duration: '8',
          time: 7.5,
          stem: 'down',
          accidental: 'flat',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['bb/3'],
          duration: '8',
          time: 8.5,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 9,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 9.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 10,
          stem: 'down',
        },
        {
          keys: ['c/3'],
          duration: '8',
          time: 10.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 11.5,
          stem: 'down',
        },
      ],
    },
    {
      number: 23,
      notes: [
        {
          keys: ['e/4'],
          duration: 'h',
          time: 0,
          stem: 'up',
        },
        {
          keys: ['f#/4'],
          duration: 'q',
          time: 2,
          stem: 'up',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 3,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 3.5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 4,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 4.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 5,
          stem: 'down',
        },
        {
          keys: ['a/3'],
          duration: '8',
          time: 5.5,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 6,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 6.5,
          stem: 'down',
        },
        {
          keys: ['g#/3'],
          duration: '8',
          time: 7,
          stem: 'down',
          accidental: 'sharp',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 7.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 8,
          stem: 'down',
        },
        {
          keys: ['g#/3'],
          duration: '8',
          time: 8.5,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 9,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 9.5,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 10,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 10.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 11,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 11.5,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 12,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 12.5,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 13,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: '8',
          time: 13.5,
          stem: 'down',
        },
        {
          keys: ['e/3'],
          duration: '8',
          time: 14,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: '8',
          time: 14.5,
          stem: 'down',
        },
      ],
    },
    {
      number: 24,
      notes: [
        {
          keys: ['e/4'],
          duration: 'h',
          time: 0,
          stem: 'up',
        },
        {
          keys: [],
          duration: 'h',
          time: 2,
        },
        {
          keys: ['bb/2'],
          duration: 'h',
          time: 4,
          stem: 'down',
          accidental: 'flat',
        },
        {
          keys: ['c/3'],
          duration: 'h',
          time: 6,
          stem: 'down',
        },
        {
          keys: ['g/3'],
          duration: 'h',
          time: 8,
          stem: 'down',
        },
        {
          keys: [],
          duration: 'h',
          time: 10,
        },
      ],
    },
    {
      number: 25,
      notes: [
        {
          keys: ['e/4'],
          duration: 'h',
          time: 0,
          stem: 'up',
        },
        {
          keys: ['d#/4'],
          duration: 'h',
          time: 2,
          stem: 'up',
          accidental: 'sharp',
        },
        {
          keys: ['e/3'],
          duration: 'h',
          time: 4,
          stem: 'up',
        },
        {
          keys: ['f#/3'],
          duration: 'h',
          time: 6,
          stem: 'up',
        },
        {
          keys: ['b/3'],
          duration: 'h',
          time: 8,
          stem: 'up',
        },
        {
          keys: ['d#/3'],
          duration: 'h',
          time: 10,
          stem: 'up',
          accidental: 'sharp',
        },
        {
          keys: ['f#/3'],
          duration: 'h',
          time: 12,
          stem: 'up',
        },
        {
          keys: ['b/3'],
          duration: 'h',
          time: 14,
          stem: 'up',
        },
        {
          keys: ['b/1'],
          duration: 'h',
          time: 16,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['b/2'],
          duration: 'h',
          time: 18,
          stem: 'down',
          accidental: 'natural',
        },
        {
          keys: ['b/1'],
          duration: 'h',
          time: 20,
          stem: 'down',
        },
        {
          keys: ['f#/2'],
          duration: 'h',
          time: 22,
          stem: 'down',
        },
        {
          keys: ['b/2'],
          duration: 'h',
          time: 24,
          stem: 'down',
        },
      ],
    },
    {
      number: 26,
      notes: [
        {
          keys: ['e/4'],
          duration: 'w',
          time: 0,
        },
        {
          keys: ['e/3'],
          duration: 'w',
          time: 4,
        },
        {
          keys: ['g/3'],
          duration: 'w',
          time: 8,
        },
        {
          keys: ['b/3'],
          duration: 'w',
          time: 12,
        },
        {
          keys: ['e/1'],
          duration: 'w',
          time: 16,
        },
        {
          keys: ['e/2'],
          duration: 'w',
          time: 20,
        },
      ],
    },
  ],
  metadata: {
    source: 'MusicXML Conversion',
    license: 'Public Domain',
  },
}
