// Central export for all components
export { default as LandingPage } from './LandingPage'
export { default as PianoKey } from './PianoKey'
export { default as PianoChord } from './PianoChord'
export { MusicPlayer } from './MusicPlayer'
export type { PlayableNote } from './MusicPlayer'
export { CircularControl } from './CircularControl'
export { SheetMusicDisplay } from './SheetMusicDisplay'
export { ProtectedRoute } from './ProtectedRoute'
export { UserStatusIndicator } from './UserStatusIndicator'
export { SaveProgressPrompt } from './SaveProgressPrompt'
export { AuthModal } from './AuthModal'
