import { KeyInfo } from './types'

// Calculate position on circle for each key
const calculatePosition = (
  index: number,
  total: number = 12,
  radius: number = 200
): { angle: number; x: number; y: number } => {
  // Start from top (C at 12 o'clock position)
  const angle = (index * 360) / total - 90
  const angleRad = (angle * Math.PI) / 180
  const x = radius * Math.cos(angleRad)
  const y = radius * Math.sin(angleRad)
  return { angle: angle + 90, x, y } // Add 90 back for display angle
}

// Define the order of keys in the circle (clockwise from C)
const keyOrder = [
  'C',
  'G',
  'D',
  'A',
  'E',
  'B',
  'F#/Gb',
  'Db',
  'Ab',
  'Eb',
  'Bb',
  'F',
]
const minorKeyOrder = [
  'Am',
  'Em',
  'Bm',
  'F#m',
  'C#m',
  'G#m',
  'D#m/Ebm',
  'Bbm',
  'Fm',
  'Cm',
  'Gm',
  'Dm',
]

// Morandi-inspired colors for each key
const keyColors = {
  C: '#A8B5A0', // Sage Green
  G: '#D4A5A5', // Dusty Rose
  D: '#C7C2BD', // Warm Gray
  A: '#A8B5C1', // Soft Blue
  E: '#D4C5A0', // Muted Gold
  B: '#B5A8B5', // Lavender Gray
  'F#/Gb': '#C1B5A8', // Taupe
  Db: '#A5B5A5', // Mint Gray
  Ab: '#B5C1A8', // Pale Olive
  Eb: '#C7BDB5', // Blush Gray
  Bb: '#B5B5C1', // Periwinkle Gray
  F: '#C1A8A8', // Mauve Gray
}

const keysData: Record<string, KeyInfo> = {
  C: {
    id: 'C',
    name: 'C Major',
    relativeMinor: 'A minor',
    keySignature: 0,
    sharpsOrFlats: 'natural',
    fifthClockwise: 'G',
    fifthCounterClockwise: 'F',
    primaryChords: ['C', 'F', 'G'],
    secondaryChords: ['Dm', 'Em', 'Am', 'Bdim'],
    scale: ['C', 'D', 'E', 'F', 'G', 'A', 'B'],
    modes: {
      ionian: ['C', 'D', 'E', 'F', 'G', 'A', 'B'],
      dorian: ['D', 'E', 'F', 'G', 'A', 'B', 'C'],
      phrygian: ['E', 'F', 'G', 'A', 'B', 'C', 'D'],
      lydian: ['F', 'G', 'A', 'B', 'C', 'D', 'E'],
      mixolydian: ['G', 'A', 'B', 'C', 'D', 'E', 'F'],
      aeolian: ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
      locrian: ['B', 'C', 'D', 'E', 'F', 'G', 'A'],
    },
    commonProgressions: [
      { name: 'I-V-vi-IV', chords: ['C', 'G', 'Am', 'F'] },
      { name: 'ii-V-I', chords: ['Dm', 'G', 'C'] },
      { name: 'I-vi-IV-V', chords: ['C', 'Am', 'F', 'G'] },
    ],
    enharmonic: null,
    color: keyColors['C'],
    position: calculatePosition(0),
    theoryNotes: {
      keyCharacteristics: 'Often described as pure, simple, and innocent',
      famousWorks: ['Prelude in C Major - Bach', 'Symphony No. 41 - Mozart'],
      relatedKeys: ['G', 'F', 'Am', 'Em', 'Dm'],
    },
  },
  G: {
    id: 'G',
    name: 'G Major',
    relativeMinor: 'E minor',
    keySignature: 1,
    sharpsOrFlats: 'sharps',
    fifthClockwise: 'D',
    fifthCounterClockwise: 'C',
    primaryChords: ['G', 'C', 'D'],
    secondaryChords: ['Am', 'Bm', 'Em', 'F#dim'],
    scale: ['G', 'A', 'B', 'C', 'D', 'E', 'F#'],
    modes: {
      ionian: ['G', 'A', 'B', 'C', 'D', 'E', 'F#'],
      dorian: ['A', 'B', 'C', 'D', 'E', 'F#', 'G'],
      phrygian: ['B', 'C', 'D', 'E', 'F#', 'G', 'A'],
      lydian: ['C', 'D', 'E', 'F#', 'G', 'A', 'B'],
      mixolydian: ['D', 'E', 'F#', 'G', 'A', 'B', 'C'],
      aeolian: ['E', 'F#', 'G', 'A', 'B', 'C', 'D'],
      locrian: ['F#', 'G', 'A', 'B', 'C', 'D', 'E'],
    },
    commonProgressions: [
      { name: 'I-V-vi-IV', chords: ['G', 'D', 'Em', 'C'] },
      { name: 'ii-V-I', chords: ['Am', 'D', 'G'] },
      { name: 'I-vi-IV-V', chords: ['G', 'Em', 'C', 'D'] },
    ],
    enharmonic: null,
    color: keyColors['G'],
    position: calculatePosition(1),
    theoryNotes: {
      keyCharacteristics: 'Bright, cheerful, and pastoral',
      famousWorks: [
        'Brandenburg Concerto No. 3 - Bach',
        'Eine kleine Nachtmusik - Mozart',
      ],
      relatedKeys: ['D', 'C', 'Em', 'Bm', 'Am'],
    },
  },
  // Continue with other keys...
  D: {
    id: 'D',
    name: 'D Major',
    relativeMinor: 'B minor',
    keySignature: 2,
    sharpsOrFlats: 'sharps',
    fifthClockwise: 'A',
    fifthCounterClockwise: 'G',
    primaryChords: ['D', 'G', 'A'],
    secondaryChords: ['Em', 'F#m', 'Bm', 'C#dim'],
    scale: ['D', 'E', 'F#', 'G', 'A', 'B', 'C#'],
    modes: {
      ionian: ['D', 'E', 'F#', 'G', 'A', 'B', 'C#'],
      dorian: ['E', 'F#', 'G', 'A', 'B', 'C#', 'D'],
      phrygian: ['F#', 'G', 'A', 'B', 'C#', 'D', 'E'],
      lydian: ['G', 'A', 'B', 'C#', 'D', 'E', 'F#'],
      mixolydian: ['A', 'B', 'C#', 'D', 'E', 'F#', 'G'],
      aeolian: ['B', 'C#', 'D', 'E', 'F#', 'G', 'A'],
      locrian: ['C#', 'D', 'E', 'F#', 'G', 'A', 'B'],
    },
    commonProgressions: [
      { name: 'I-V-vi-IV', chords: ['D', 'A', 'Bm', 'G'] },
      { name: 'ii-V-I', chords: ['Em', 'A', 'D'] },
      { name: 'I-vi-IV-V', chords: ['D', 'Bm', 'G', 'A'] },
    ],
    enharmonic: null,
    color: keyColors['D'],
    position: calculatePosition(2),
    theoryNotes: {
      keyCharacteristics: 'Triumphant, victorious, and majestic',
      famousWorks: [
        'Hallelujah Chorus - Handel',
        'Violin Concerto - Beethoven',
      ],
      relatedKeys: ['A', 'G', 'Bm', 'F#m', 'Em'],
    },
  },
  A: {
    id: 'A',
    name: 'A Major',
    relativeMinor: 'F# minor',
    keySignature: 3,
    sharpsOrFlats: 'sharps',
    fifthClockwise: 'E',
    fifthCounterClockwise: 'D',
    primaryChords: ['A', 'D', 'E'],
    secondaryChords: ['Bm', 'C#m', 'F#m', 'G#dim'],
    scale: ['A', 'B', 'C#', 'D', 'E', 'F#', 'G#'],
    modes: {
      ionian: ['A', 'B', 'C#', 'D', 'E', 'F#', 'G#'],
      dorian: ['B', 'C#', 'D', 'E', 'F#', 'G#', 'A'],
      phrygian: ['C#', 'D', 'E', 'F#', 'G#', 'A', 'B'],
      lydian: ['D', 'E', 'F#', 'G#', 'A', 'B', 'C#'],
      mixolydian: ['E', 'F#', 'G#', 'A', 'B', 'C#', 'D'],
      aeolian: ['F#', 'G#', 'A', 'B', 'C#', 'D', 'E'],
      locrian: ['G#', 'A', 'B', 'C#', 'D', 'E', 'F#'],
    },
    commonProgressions: [
      { name: 'I-V-vi-IV', chords: ['A', 'E', 'F#m', 'D'] },
      { name: 'ii-V-I', chords: ['Bm', 'E', 'A'] },
      { name: 'I-vi-IV-V', chords: ['A', 'F#m', 'D', 'E'] },
    ],
    enharmonic: null,
    color: keyColors['A'],
    position: calculatePosition(3),
    theoryNotes: {
      keyCharacteristics: 'Joyful, passionate, and confident',
      famousWorks: [
        'Piano Sonata No. 11 - Mozart',
        'Symphony No. 7 - Beethoven',
      ],
      relatedKeys: ['E', 'D', 'F#m', 'C#m', 'Bm'],
    },
  },
  E: {
    id: 'E',
    name: 'E Major',
    relativeMinor: 'C# minor',
    keySignature: 4,
    sharpsOrFlats: 'sharps',
    fifthClockwise: 'B',
    fifthCounterClockwise: 'A',
    primaryChords: ['E', 'A', 'B'],
    secondaryChords: ['F#m', 'G#m', 'C#m', 'D#dim'],
    scale: ['E', 'F#', 'G#', 'A', 'B', 'C#', 'D#'],
    modes: {
      ionian: ['E', 'F#', 'G#', 'A', 'B', 'C#', 'D#'],
      dorian: ['F#', 'G#', 'A', 'B', 'C#', 'D#', 'E'],
      phrygian: ['G#', 'A', 'B', 'C#', 'D#', 'E', 'F#'],
      lydian: ['A', 'B', 'C#', 'D#', 'E', 'F#', 'G#'],
      mixolydian: ['B', 'C#', 'D#', 'E', 'F#', 'G#', 'A'],
      aeolian: ['C#', 'D#', 'E', 'F#', 'G#', 'A', 'B'],
      locrian: ['D#', 'E', 'F#', 'G#', 'A', 'B', 'C#'],
    },
    commonProgressions: [
      { name: 'I-V-vi-IV', chords: ['E', 'B', 'C#m', 'A'] },
      { name: 'ii-V-I', chords: ['F#m', 'B', 'E'] },
      { name: 'I-vi-IV-V', chords: ['E', 'C#m', 'A', 'B'] },
    ],
    enharmonic: null,
    color: keyColors['E'],
    position: calculatePosition(4),
    theoryNotes: {
      keyCharacteristics: 'Brilliant, energetic, and powerful',
      famousWorks: [
        'Spring from The Four Seasons - Vivaldi',
        'Violin Concerto in E Major - Bach',
      ],
      relatedKeys: ['B', 'A', 'C#m', 'G#m', 'F#m'],
    },
  },
  B: {
    id: 'B',
    name: 'B Major',
    relativeMinor: 'G# minor',
    keySignature: 5,
    sharpsOrFlats: 'sharps',
    fifthClockwise: 'F#',
    fifthCounterClockwise: 'E',
    primaryChords: ['B', 'E', 'F#'],
    secondaryChords: ['C#m', 'D#m', 'G#m', 'A#dim'],
    scale: ['B', 'C#', 'D#', 'E', 'F#', 'G#', 'A#'],
    modes: {
      ionian: ['B', 'C#', 'D#', 'E', 'F#', 'G#', 'A#'],
      dorian: ['C#', 'D#', 'E', 'F#', 'G#', 'A#', 'B'],
      phrygian: ['D#', 'E', 'F#', 'G#', 'A#', 'B', 'C#'],
      lydian: ['E', 'F#', 'G#', 'A#', 'B', 'C#', 'D#'],
      mixolydian: ['F#', 'G#', 'A#', 'B', 'C#', 'D#', 'E'],
      aeolian: ['G#', 'A#', 'B', 'C#', 'D#', 'E', 'F#'],
      locrian: ['A#', 'B', 'C#', 'D#', 'E', 'F#', 'G#'],
    },
    commonProgressions: [
      { name: 'I-V-vi-IV', chords: ['B', 'F#', 'G#m', 'E'] },
      { name: 'ii-V-I', chords: ['C#m', 'F#', 'B'] },
      { name: 'I-vi-IV-V', chords: ['B', 'G#m', 'E', 'F#'] },
    ],
    enharmonic: 'Cb',
    color: keyColors['B'],
    position: calculatePosition(5),
    theoryNotes: {
      keyCharacteristics: 'Harsh, strong, and wild',
      famousWorks: ['Piano Sonata No. 4 - Chopin', 'Piano Trio - Brahms'],
      relatedKeys: ['F#', 'E', 'G#m', 'D#m', 'C#m'],
    },
  },
  'F#': {
    id: 'F#',
    name: 'F# Major',
    relativeMinor: 'D# minor',
    keySignature: 6,
    sharpsOrFlats: 'sharps',
    fifthClockwise: 'C#',
    fifthCounterClockwise: 'B',
    primaryChords: ['F#', 'B', 'C#'],
    secondaryChords: ['G#m', 'A#m', 'D#m', 'E#dim'],
    scale: ['F#', 'G#', 'A#', 'B', 'C#', 'D#', 'E#'],
    modes: {
      ionian: ['F#', 'G#', 'A#', 'B', 'C#', 'D#', 'E#'],
      dorian: ['G#', 'A#', 'B', 'C#', 'D#', 'E#', 'F#'],
      phrygian: ['A#', 'B', 'C#', 'D#', 'E#', 'F#', 'G#'],
      lydian: ['B', 'C#', 'D#', 'E#', 'F#', 'G#', 'A#'],
      mixolydian: ['C#', 'D#', 'E#', 'F#', 'G#', 'A#', 'B'],
      aeolian: ['D#', 'E#', 'F#', 'G#', 'A#', 'B', 'C#'],
      locrian: ['E#', 'F#', 'G#', 'A#', 'B', 'C#', 'D#'],
    },
    commonProgressions: [
      { name: 'I-V-vi-IV', chords: ['F#', 'C#', 'D#m', 'B'] },
      { name: 'ii-V-I', chords: ['G#m', 'C#', 'F#'] },
      { name: 'I-vi-IV-V', chords: ['F#', 'D#m', 'B', 'C#'] },
    ],
    enharmonic: 'Gb',
    color: keyColors['F#/Gb'],
    position: calculatePosition(6),
    theoryNotes: {
      keyCharacteristics: 'Triumph over difficulty, relief',
      famousWorks: ['Barcarolle - Chopin', 'Piano Sonata No. 24 - Beethoven'],
      relatedKeys: ['C#', 'B', 'D#m', 'A#m', 'G#m'],
    },
  },
  Gb: {
    id: 'Gb',
    name: 'Gb Major',
    relativeMinor: 'Eb minor',
    keySignature: 6,
    sharpsOrFlats: 'flats',
    fifthClockwise: 'Db',
    fifthCounterClockwise: 'Cb',
    primaryChords: ['Gb', 'Cb', 'Db'],
    secondaryChords: ['Abm', 'Bbm', 'Ebm', 'Fdim'],
    scale: ['Gb', 'Ab', 'Bb', 'Cb', 'Db', 'Eb', 'F'],
    modes: {
      ionian: ['Gb', 'Ab', 'Bb', 'Cb', 'Db', 'Eb', 'F'],
      dorian: ['Ab', 'Bb', 'Cb', 'Db', 'Eb', 'F', 'Gb'],
      phrygian: ['Bb', 'Cb', 'Db', 'Eb', 'F', 'Gb', 'Ab'],
      lydian: ['Cb', 'Db', 'Eb', 'F', 'Gb', 'Ab', 'Bb'],
      mixolydian: ['Db', 'Eb', 'F', 'Gb', 'Ab', 'Bb', 'Cb'],
      aeolian: ['Eb', 'F', 'Gb', 'Ab', 'Bb', 'Cb', 'Db'],
      locrian: ['F', 'Gb', 'Ab', 'Bb', 'Cb', 'Db', 'Eb'],
    },
    commonProgressions: [
      { name: 'I-V-vi-IV', chords: ['Gb', 'Db', 'Ebm', 'Cb'] },
      { name: 'ii-V-I', chords: ['Abm', 'Db', 'Gb'] },
      { name: 'I-vi-IV-V', chords: ['Gb', 'Ebm', 'Cb', 'Db'] },
    ],
    enharmonic: 'F#',
    color: keyColors['F#/Gb'],
    position: calculatePosition(6),
    theoryNotes: {
      keyCharacteristics: 'Gentle, soft, and peaceful',
      famousWorks: ['Impromptu in Gb - Chopin', 'Waltz in Gb - Chopin'],
      relatedKeys: ['Db', 'Cb', 'Ebm', 'Bbm', 'Abm'],
    },
  },
  Db: {
    id: 'Db',
    name: 'Db Major',
    relativeMinor: 'Bb minor',
    keySignature: 5,
    sharpsOrFlats: 'flats',
    fifthClockwise: 'Ab',
    fifthCounterClockwise: 'Gb',
    primaryChords: ['Db', 'Gb', 'Ab'],
    secondaryChords: ['Ebm', 'Fm', 'Bbm', 'Cdim'],
    scale: ['Db', 'Eb', 'F', 'Gb', 'Ab', 'Bb', 'C'],
    modes: {
      ionian: ['Db', 'Eb', 'F', 'Gb', 'Ab', 'Bb', 'C'],
      dorian: ['Eb', 'F', 'Gb', 'Ab', 'Bb', 'C', 'Db'],
      phrygian: ['F', 'Gb', 'Ab', 'Bb', 'C', 'Db', 'Eb'],
      lydian: ['Gb', 'Ab', 'Bb', 'C', 'Db', 'Eb', 'F'],
      mixolydian: ['Ab', 'Bb', 'C', 'Db', 'Eb', 'F', 'Gb'],
      aeolian: ['Bb', 'C', 'Db', 'Eb', 'F', 'Gb', 'Ab'],
      locrian: ['C', 'Db', 'Eb', 'F', 'Gb', 'Ab', 'Bb'],
    },
    commonProgressions: [
      { name: 'I-V-vi-IV', chords: ['Db', 'Ab', 'Bbm', 'Gb'] },
      { name: 'ii-V-I', chords: ['Ebm', 'Ab', 'Db'] },
      { name: 'I-vi-IV-V', chords: ['Db', 'Bbm', 'Gb', 'Ab'] },
    ],
    enharmonic: 'C#',
    color: keyColors['Db'],
    position: calculatePosition(7),
    theoryNotes: {
      keyCharacteristics: 'Grief, depressive, and emotional',
      famousWorks: ['Clair de Lune - Debussy', 'Raindrop Prelude - Chopin'],
      relatedKeys: ['Ab', 'Gb', 'Bbm', 'Fm', 'Ebm'],
    },
  },
  Ab: {
    id: 'Ab',
    name: 'Ab Major',
    relativeMinor: 'F minor',
    keySignature: 4,
    sharpsOrFlats: 'flats',
    fifthClockwise: 'Eb',
    fifthCounterClockwise: 'Db',
    primaryChords: ['Ab', 'Db', 'Eb'],
    secondaryChords: ['Bbm', 'Cm', 'Fm', 'Gdim'],
    scale: ['Ab', 'Bb', 'C', 'Db', 'Eb', 'F', 'G'],
    modes: {
      ionian: ['Ab', 'Bb', 'C', 'Db', 'Eb', 'F', 'G'],
      dorian: ['Bb', 'C', 'Db', 'Eb', 'F', 'G', 'Ab'],
      phrygian: ['C', 'Db', 'Eb', 'F', 'G', 'Ab', 'Bb'],
      lydian: ['Db', 'Eb', 'F', 'G', 'Ab', 'Bb', 'C'],
      mixolydian: ['Eb', 'F', 'G', 'Ab', 'Bb', 'C', 'Db'],
      aeolian: ['F', 'G', 'Ab', 'Bb', 'C', 'Db', 'Eb'],
      locrian: ['G', 'Ab', 'Bb', 'C', 'Db', 'Eb', 'F'],
    },
    commonProgressions: [
      { name: 'I-V-vi-IV', chords: ['Ab', 'Eb', 'Fm', 'Db'] },
      { name: 'ii-V-I', chords: ['Bbm', 'Eb', 'Ab'] },
      { name: 'I-vi-IV-V', chords: ['Ab', 'Fm', 'Db', 'Eb'] },
    ],
    enharmonic: 'G#',
    color: keyColors['Ab'],
    position: calculatePosition(8),
    theoryNotes: {
      keyCharacteristics: 'Grave, death, judgment, eternity',
      famousWorks: ['Impromptu No. 1 - Schubert', 'Polonaise in Ab - Chopin'],
      relatedKeys: ['Eb', 'Db', 'Fm', 'Cm', 'Bbm'],
    },
  },
  Eb: {
    id: 'Eb',
    name: 'Eb Major',
    relativeMinor: 'C minor',
    keySignature: 3,
    sharpsOrFlats: 'flats',
    fifthClockwise: 'Bb',
    fifthCounterClockwise: 'Ab',
    primaryChords: ['Eb', 'Ab', 'Bb'],
    secondaryChords: ['Fm', 'Gm', 'Cm', 'Ddim'],
    scale: ['Eb', 'F', 'G', 'Ab', 'Bb', 'C', 'D'],
    modes: {
      ionian: ['Eb', 'F', 'G', 'Ab', 'Bb', 'C', 'D'],
      dorian: ['F', 'G', 'Ab', 'Bb', 'C', 'D', 'Eb'],
      phrygian: ['G', 'Ab', 'Bb', 'C', 'D', 'Eb', 'F'],
      lydian: ['Ab', 'Bb', 'C', 'D', 'Eb', 'F', 'G'],
      mixolydian: ['Bb', 'C', 'D', 'Eb', 'F', 'G', 'Ab'],
      aeolian: ['C', 'D', 'Eb', 'F', 'G', 'Ab', 'Bb'],
      locrian: ['D', 'Eb', 'F', 'G', 'Ab', 'Bb', 'C'],
    },
    commonProgressions: [
      { name: 'I-V-vi-IV', chords: ['Eb', 'Bb', 'Cm', 'Ab'] },
      { name: 'ii-V-I', chords: ['Fm', 'Bb', 'Eb'] },
      { name: 'I-vi-IV-V', chords: ['Eb', 'Cm', 'Ab', 'Bb'] },
    ],
    enharmonic: 'D#',
    color: keyColors['Eb'],
    position: calculatePosition(9),
    theoryNotes: {
      keyCharacteristics: 'Heroic, majestic, and devotional',
      famousWorks: [
        'Symphony No. 3 "Eroica" - Beethoven',
        'Piano Concerto No. 5 - Beethoven',
      ],
      relatedKeys: ['Bb', 'Ab', 'Cm', 'Gm', 'Fm'],
    },
  },
  Bb: {
    id: 'Bb',
    name: 'Bb Major',
    relativeMinor: 'G minor',
    keySignature: 2,
    sharpsOrFlats: 'flats',
    fifthClockwise: 'F',
    fifthCounterClockwise: 'Eb',
    primaryChords: ['Bb', 'Eb', 'F'],
    secondaryChords: ['Cm', 'Dm', 'Gm', 'Adim'],
    scale: ['Bb', 'C', 'D', 'Eb', 'F', 'G', 'A'],
    modes: {
      ionian: ['Bb', 'C', 'D', 'Eb', 'F', 'G', 'A'],
      dorian: ['C', 'D', 'Eb', 'F', 'G', 'A', 'Bb'],
      phrygian: ['D', 'Eb', 'F', 'G', 'A', 'Bb', 'C'],
      lydian: ['Eb', 'F', 'G', 'A', 'Bb', 'C', 'D'],
      mixolydian: ['F', 'G', 'A', 'Bb', 'C', 'D', 'Eb'],
      aeolian: ['G', 'A', 'Bb', 'C', 'D', 'Eb', 'F'],
      locrian: ['A', 'Bb', 'C', 'D', 'Eb', 'F', 'G'],
    },
    commonProgressions: [
      { name: 'I-V-vi-IV', chords: ['Bb', 'F', 'Gm', 'Eb'] },
      { name: 'ii-V-I', chords: ['Cm', 'F', 'Bb'] },
      { name: 'I-vi-IV-V', chords: ['Bb', 'Gm', 'Eb', 'F'] },
    ],
    enharmonic: 'A#',
    color: keyColors['Bb'],
    position: calculatePosition(10),
    theoryNotes: {
      keyCharacteristics: 'Joyful, magnificent, and cheerful',
      famousWorks: [
        'Symphony No. 4 - Beethoven',
        'Piano Concerto No. 2 - Brahms',
      ],
      relatedKeys: ['F', 'Eb', 'Gm', 'Dm', 'Cm'],
    },
  },
  F: {
    id: 'F',
    name: 'F Major',
    relativeMinor: 'D minor',
    keySignature: 1,
    sharpsOrFlats: 'flats',
    fifthClockwise: 'C',
    fifthCounterClockwise: 'Bb',
    primaryChords: ['F', 'Bb', 'C'],
    secondaryChords: ['Gm', 'Am', 'Dm', 'Edim'],
    scale: ['F', 'G', 'A', 'Bb', 'C', 'D', 'E'],
    modes: {
      ionian: ['F', 'G', 'A', 'Bb', 'C', 'D', 'E'],
      dorian: ['G', 'A', 'Bb', 'C', 'D', 'E', 'F'],
      phrygian: ['A', 'Bb', 'C', 'D', 'E', 'F', 'G'],
      lydian: ['Bb', 'C', 'D', 'E', 'F', 'G', 'A'],
      mixolydian: ['C', 'D', 'E', 'F', 'G', 'A', 'Bb'],
      aeolian: ['D', 'E', 'F', 'G', 'A', 'Bb', 'C'],
      locrian: ['E', 'F', 'G', 'A', 'Bb', 'C', 'D'],
    },
    commonProgressions: [
      { name: 'I-V-vi-IV', chords: ['F', 'C', 'Dm', 'Bb'] },
      { name: 'ii-V-I', chords: ['Gm', 'C', 'F'] },
      { name: 'I-vi-IV-V', chords: ['F', 'Dm', 'Bb', 'C'] },
    ],
    enharmonic: 'E#',
    color: keyColors['F'],
    position: calculatePosition(11),
    theoryNotes: {
      keyCharacteristics: 'Calm, pastoral, and complacent',
      famousWorks: [
        'Pastoral Symphony - Beethoven',
        'Brandenburg Concerto No. 1 - Bach',
      ],
      relatedKeys: ['C', 'Bb', 'Dm', 'Am', 'Gm'],
    },
  },
  // Minor Keys
  Am: {
    id: 'Am',
    name: 'A minor',
    relativeMinor: 'C Major', // For minor keys, this refers to relative major
    keySignature: 0,
    sharpsOrFlats: 'natural',
    fifthClockwise: 'Em',
    fifthCounterClockwise: 'Dm',
    primaryChords: ['Am', 'Dm', 'Em', 'E'],
    secondaryChords: ['Bdim', 'C', 'F', 'G'],
    scale: ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
    modes: {
      ionian: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], // Natural minor
      dorian: ['A', 'B', 'C', 'D', 'E', 'F#', 'G'],
      phrygian: ['A', 'Bb', 'C', 'D', 'E', 'F', 'G'],
      lydian: ['A', 'B', 'C', 'D#', 'E', 'F', 'G'],
      mixolydian: ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
      aeolian: ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
      locrian: ['A', 'Bb', 'C', 'D', 'Eb', 'F', 'G'],
    },
    commonProgressions: [
      { name: 'i-iv-v', chords: ['Am', 'Dm', 'Em'] },
      { name: 'i-iv-VII', chords: ['Am', 'Dm', 'G'] },
      { name: 'i-VI-III-VII', chords: ['Am', 'F', 'C', 'G'] },
    ],
    enharmonic: null,
    color: keyColors['C'], // Same color as relative major
    position: calculatePosition(0, 12, 90), // Inner radius position
    theoryNotes: {
      keyCharacteristics: 'Melancholic, tender, and plaintive',
      famousWorks: [
        'Violin Concerto in A minor - Bach',
        'Piano Sonata No. 8 - Mozart',
      ],
      relatedKeys: ['C', 'Em', 'Dm', 'F', 'G'],
    },
  },
  Em: {
    id: 'Em',
    name: 'E minor',
    relativeMinor: 'G Major',
    keySignature: 1,
    sharpsOrFlats: 'sharps',
    fifthClockwise: 'Bm',
    fifthCounterClockwise: 'Am',
    primaryChords: ['Em', 'Am', 'Bm', 'B'],
    secondaryChords: ['F#dim', 'G', 'C', 'D'],
    scale: ['E', 'F#', 'G', 'A', 'B', 'C', 'D'],
    modes: {
      ionian: ['E', 'F#', 'G', 'A', 'B', 'C', 'D'],
      dorian: ['E', 'F#', 'G', 'A', 'B', 'C#', 'D'],
      phrygian: ['E', 'F', 'G', 'A', 'B', 'C', 'D'],
      lydian: ['E', 'F#', 'G', 'A#', 'B', 'C', 'D'],
      mixolydian: ['E', 'F#', 'G', 'A', 'B', 'C', 'D'],
      aeolian: ['E', 'F#', 'G', 'A', 'B', 'C', 'D'],
      locrian: ['E', 'F', 'G', 'A', 'Bb', 'C', 'D'],
    },
    commonProgressions: [
      { name: 'i-iv-v', chords: ['Em', 'Am', 'Bm'] },
      { name: 'i-VII-IV-V', chords: ['Em', 'D', 'A', 'B'] },
      { name: 'i-VI-VII', chords: ['Em', 'C', 'D'] },
    ],
    enharmonic: null,
    color: keyColors['G'],
    position: calculatePosition(1, 12, 90),
    theoryNotes: {
      keyCharacteristics: 'Effusive, lively, and restless',
      famousWorks: [
        'Symphony No. 9 "From the New World" - Dvorak',
        'Violin Sonata in E minor - Bach',
      ],
      relatedKeys: ['G', 'Bm', 'Am', 'C', 'D'],
    },
  },
  Bm: {
    id: 'Bm',
    name: 'B minor',
    relativeMinor: 'D Major',
    keySignature: 2,
    sharpsOrFlats: 'sharps',
    fifthClockwise: 'F#m',
    fifthCounterClockwise: 'Em',
    primaryChords: ['Bm', 'Em', 'F#m', 'F#'],
    secondaryChords: ['C#dim', 'D', 'G', 'A'],
    scale: ['B', 'C#', 'D', 'E', 'F#', 'G', 'A'],
    modes: {
      ionian: ['B', 'C#', 'D', 'E', 'F#', 'G', 'A'],
      dorian: ['B', 'C#', 'D', 'E', 'F#', 'G#', 'A'],
      phrygian: ['B', 'C', 'D', 'E', 'F#', 'G', 'A'],
      lydian: ['B', 'C#', 'D', 'E#', 'F#', 'G', 'A'],
      mixolydian: ['B', 'C#', 'D', 'E', 'F#', 'G', 'A'],
      aeolian: ['B', 'C#', 'D', 'E', 'F#', 'G', 'A'],
      locrian: ['B', 'C', 'D', 'E', 'F', 'G', 'A'],
    },
    commonProgressions: [
      { name: 'i-iv-v', chords: ['Bm', 'Em', 'F#m'] },
      { name: 'i-VII-VI', chords: ['Bm', 'A', 'G'] },
      { name: 'i-VI-VII-i', chords: ['Bm', 'G', 'A', 'Bm'] },
    ],
    enharmonic: null,
    color: keyColors['D'],
    position: calculatePosition(2, 12, 90),
    theoryNotes: {
      keyCharacteristics: 'Patient, calm, and accepting',
      famousWorks: [
        'Mass in B minor - Bach',
        'Symphony No. 8 "Unfinished" - Schubert',
        'Waltz Op. 69 No. 2 - Chopin',
      ],
      relatedKeys: ['D', 'F#m', 'Em', 'G', 'A'],
    },
  },
  'F#m': {
    id: 'F#m',
    name: 'F# minor',
    relativeMinor: 'A Major',
    keySignature: 3,
    sharpsOrFlats: 'sharps',
    fifthClockwise: 'C#m',
    fifthCounterClockwise: 'Bm',
    primaryChords: ['F#m', 'Bm', 'C#m', 'C#'],
    secondaryChords: ['G#dim', 'A', 'D', 'E'],
    scale: ['F#', 'G#', 'A', 'B', 'C#', 'D', 'E'],
    modes: {
      ionian: ['F#', 'G#', 'A', 'B', 'C#', 'D', 'E'],
      dorian: ['F#', 'G#', 'A', 'B', 'C#', 'D#', 'E'],
      phrygian: ['F#', 'G', 'A', 'B', 'C#', 'D', 'E'],
      lydian: ['F#', 'G#', 'A', 'B#', 'C#', 'D', 'E'],
      mixolydian: ['F#', 'G#', 'A', 'B', 'C#', 'D', 'E'],
      aeolian: ['F#', 'G#', 'A', 'B', 'C#', 'D', 'E'],
      locrian: ['F#', 'G', 'A', 'B', 'C', 'D', 'E'],
    },
    commonProgressions: [
      { name: 'i-iv-v', chords: ['F#m', 'Bm', 'C#m'] },
      { name: 'i-VII-VI', chords: ['F#m', 'E', 'D'] },
      { name: 'i-iv-VII-III', chords: ['F#m', 'Bm', 'E', 'A'] },
    ],
    enharmonic: null,
    color: keyColors['A'],
    position: calculatePosition(3, 12, 90),
    theoryNotes: {
      keyCharacteristics: 'Private grief, anguish of the soul',
      famousWorks: [
        'Barcarolle Op. 60 - Chopin',
        'Piano Sonata Op. 78 - Beethoven',
      ],
      relatedKeys: ['A', 'C#m', 'Bm', 'D', 'E'],
    },
  },
  'C#m': {
    id: 'C#m',
    name: 'C# minor',
    relativeMinor: 'E Major',
    keySignature: 4,
    sharpsOrFlats: 'sharps',
    fifthClockwise: 'G#m',
    fifthCounterClockwise: 'F#m',
    primaryChords: ['C#m', 'F#m', 'G#m', 'G#'],
    secondaryChords: ['D#dim', 'E', 'A', 'B'],
    scale: ['C#', 'D#', 'E', 'F#', 'G#', 'A', 'B'],
    modes: {
      ionian: ['C#', 'D#', 'E', 'F#', 'G#', 'A', 'B'],
      dorian: ['C#', 'D#', 'E', 'F#', 'G#', 'A#', 'B'],
      phrygian: ['C#', 'D', 'E', 'F#', 'G#', 'A', 'B'],
      lydian: ['C#', 'D#', 'E', 'F##', 'G#', 'A', 'B'],
      mixolydian: ['C#', 'D#', 'E', 'F#', 'G#', 'A', 'B'],
      aeolian: ['C#', 'D#', 'E', 'F#', 'G#', 'A', 'B'],
      locrian: ['C#', 'D', 'E', 'F#', 'G', 'A', 'B'],
    },
    commonProgressions: [
      { name: 'i-iv-v', chords: ['C#m', 'F#m', 'G#m'] },
      { name: 'i-VII-VI', chords: ['C#m', 'B', 'A'] },
      { name: 'i-VI-VII-i', chords: ['C#m', 'A', 'B', 'C#m'] },
    ],
    enharmonic: null,
    color: keyColors['E'],
    position: calculatePosition(4, 12, 90),
    theoryNotes: {
      keyCharacteristics: 'Despair, wailing, loud grief',
      famousWorks: [
        'Moonlight Sonata (1st movement) - Beethoven',
        'Etude Op. 25 No. 7 - Chopin',
      ],
      relatedKeys: ['E', 'G#m', 'F#m', 'A', 'B'],
    },
  },
  'G#m': {
    id: 'G#m',
    name: 'G# minor',
    relativeMinor: 'B Major',
    keySignature: 5,
    sharpsOrFlats: 'sharps',
    fifthClockwise: 'D#m',
    fifthCounterClockwise: 'C#m',
    primaryChords: ['G#m', 'C#m', 'D#m', 'D#'],
    secondaryChords: ['A#dim', 'B', 'E', 'F#'],
    scale: ['G#', 'A#', 'B', 'C#', 'D#', 'E', 'F#'],
    modes: {
      ionian: ['G#', 'A#', 'B', 'C#', 'D#', 'E', 'F#'],
      dorian: ['G#', 'A#', 'B', 'C#', 'D#', 'E#', 'F#'],
      phrygian: ['G#', 'A', 'B', 'C#', 'D#', 'E', 'F#'],
      lydian: ['G#', 'A#', 'B', 'C##', 'D#', 'E', 'F#'],
      mixolydian: ['G#', 'A#', 'B', 'C#', 'D#', 'E', 'F#'],
      aeolian: ['G#', 'A#', 'B', 'C#', 'D#', 'E', 'F#'],
      locrian: ['G#', 'A', 'B', 'C#', 'D', 'E', 'F#'],
    },
    commonProgressions: [
      { name: 'i-iv-v', chords: ['G#m', 'C#m', 'D#m'] },
      { name: 'i-VII-VI', chords: ['G#m', 'F#', 'E'] },
      { name: 'i-iv-VII', chords: ['G#m', 'C#m', 'F#'] },
    ],
    enharmonic: 'Abm',
    color: keyColors['B'],
    position: calculatePosition(5, 12, 90),
    theoryNotes: {
      keyCharacteristics: 'Heart-rending, lonely, desperate struggle',
      famousWorks: [
        'Rachmaninoff Prelude Op. 32 No. 12 - Rachmaninoff',
        'Etude Op. 25 No. 6 - Chopin',
      ],
      relatedKeys: ['B', 'D#m', 'C#m', 'E', 'F#'],
    },
  },
  'D#m': {
    id: 'D#m',
    name: 'D# minor',
    relativeMinor: 'F# Major',
    keySignature: 6,
    sharpsOrFlats: 'sharps',
    fifthClockwise: 'A#m',
    fifthCounterClockwise: 'G#m',
    primaryChords: ['D#m', 'G#m', 'A#m', 'A#'],
    secondaryChords: ['E#dim', 'F#', 'B', 'C#'],
    scale: ['D#', 'E#', 'F#', 'G#', 'A#', 'B', 'C#'],
    modes: {
      ionian: ['D#', 'E#', 'F#', 'G#', 'A#', 'B', 'C#'],
      dorian: ['D#', 'E#', 'F#', 'G#', 'A#', 'B#', 'C#'],
      phrygian: ['D#', 'E', 'F#', 'G#', 'A#', 'B', 'C#'],
      lydian: ['D#', 'E#', 'F#', 'G##', 'A#', 'B', 'C#'],
      mixolydian: ['D#', 'E#', 'F#', 'G#', 'A#', 'B', 'C#'],
      aeolian: ['D#', 'E#', 'F#', 'G#', 'A#', 'B', 'C#'],
      locrian: ['D#', 'E', 'F#', 'G#', 'A', 'B', 'C#'],
    },
    commonProgressions: [
      { name: 'i-iv-v', chords: ['D#m', 'G#m', 'A#m'] },
      { name: 'i-VII-VI', chords: ['D#m', 'C#', 'B'] },
      { name: 'i-VI-iv-V', chords: ['D#m', 'B', 'G#m', 'A#'] },
    ],
    enharmonic: 'Ebm',
    color: keyColors['F#/Gb'],
    position: calculatePosition(6, 12, 90),
    theoryNotes: {
      keyCharacteristics: 'Deep distress, existential angst',
      famousWorks: [
        'Nocturne Op. 9 No. 3 - Chopin',
        'Piano Sonata No. 2 - Prokofiev',
      ],
      relatedKeys: ['F#', 'A#m', 'G#m', 'B', 'C#'],
    },
  },
  Ebm: {
    id: 'Ebm',
    name: 'Eb minor',
    relativeMinor: 'Gb Major',
    keySignature: 6,
    sharpsOrFlats: 'flats',
    fifthClockwise: 'Bbm',
    fifthCounterClockwise: 'Abm',
    primaryChords: ['Ebm', 'Abm', 'Bbm', 'Bb'],
    secondaryChords: ['Fdim', 'Gb', 'Cb', 'Db'],
    scale: ['Eb', 'F', 'Gb', 'Ab', 'Bb', 'Cb', 'Db'],
    modes: {
      ionian: ['Eb', 'F', 'Gb', 'Ab', 'Bb', 'Cb', 'Db'],
      dorian: ['Eb', 'F', 'Gb', 'Ab', 'Bb', 'C', 'Db'],
      phrygian: ['Eb', 'Fb', 'Gb', 'Ab', 'Bb', 'Cb', 'Db'],
      lydian: ['Eb', 'F', 'Gb', 'A', 'Bb', 'Cb', 'Db'],
      mixolydian: ['Eb', 'F', 'Gb', 'Ab', 'Bb', 'Cb', 'Db'],
      aeolian: ['Eb', 'F', 'Gb', 'Ab', 'Bb', 'Cb', 'Db'],
      locrian: ['Eb', 'Fb', 'Gb', 'Ab', 'Bbb', 'Cb', 'Db'],
    },
    commonProgressions: [
      { name: 'i-iv-v', chords: ['Ebm', 'Abm', 'Bbm'] },
      { name: 'i-VII-VI', chords: ['Ebm', 'Db', 'Cb'] },
      { name: 'i-iv-VII', chords: ['Ebm', 'Abm', 'Db'] },
    ],
    enharmonic: 'D#m',
    color: keyColors['F#/Gb'],
    position: calculatePosition(6, 12, 90),
    theoryNotes: {
      keyCharacteristics: 'Anxiety, soul anguish, deep despair',
      famousWorks: [
        'Prelude Op. 28 No. 14 - Chopin',
        'Piano Trio Op. 67 - Shostakovich',
      ],
      relatedKeys: ['Gb', 'Bbm', 'Abm', 'Cb', 'Db'],
    },
  },
  Bbm: {
    id: 'Bbm',
    name: 'Bb minor',
    relativeMinor: 'Db Major',
    keySignature: 5,
    sharpsOrFlats: 'flats',
    fifthClockwise: 'Fm',
    fifthCounterClockwise: 'Ebm',
    primaryChords: ['Bbm', 'Ebm', 'Fm', 'F'],
    secondaryChords: ['Cdim', 'Db', 'Gb', 'Ab'],
    scale: ['Bb', 'C', 'Db', 'Eb', 'F', 'Gb', 'Ab'],
    modes: {
      ionian: ['Bb', 'C', 'Db', 'Eb', 'F', 'Gb', 'Ab'],
      dorian: ['Bb', 'C', 'Db', 'Eb', 'F', 'G', 'Ab'],
      phrygian: ['Bb', 'Cb', 'Db', 'Eb', 'F', 'Gb', 'Ab'],
      lydian: ['Bb', 'C', 'Db', 'E', 'F', 'Gb', 'Ab'],
      mixolydian: ['Bb', 'C', 'Db', 'Eb', 'F', 'Gb', 'Ab'],
      aeolian: ['Bb', 'C', 'Db', 'Eb', 'F', 'Gb', 'Ab'],
      locrian: ['Bb', 'Cb', 'Db', 'Eb', 'Fb', 'Gb', 'Ab'],
    },
    commonProgressions: [
      { name: 'i-iv-v', chords: ['Bbm', 'Ebm', 'Fm'] },
      { name: 'i-VII-VI', chords: ['Bbm', 'Ab', 'Gb'] },
      { name: 'i-VI-VII-i', chords: ['Bbm', 'Gb', 'Ab', 'Bbm'] },
    ],
    enharmonic: 'A#m',
    color: keyColors['Db'],
    position: calculatePosition(7, 12, 90),
    theoryNotes: {
      keyCharacteristics: 'Gloomy, mocking, uneasiness',
      famousWorks: ['Nocturne Op. 9 No. 1 - Chopin'],
      relatedKeys: ['Db', 'Fm', 'Ebm', 'Gb', 'Ab'],
    },
  },
  Fm: {
    id: 'Fm',
    name: 'F minor',
    relativeMinor: 'Ab Major',
    keySignature: 4,
    sharpsOrFlats: 'flats',
    fifthClockwise: 'Cm',
    fifthCounterClockwise: 'Bbm',
    primaryChords: ['Fm', 'Bbm', 'Cm', 'C'],
    secondaryChords: ['Gdim', 'Ab', 'Db', 'Eb'],
    scale: ['F', 'G', 'Ab', 'Bb', 'C', 'Db', 'Eb'],
    modes: {
      ionian: ['F', 'G', 'Ab', 'Bb', 'C', 'Db', 'Eb'],
      dorian: ['F', 'G', 'Ab', 'Bb', 'C', 'D', 'Eb'],
      phrygian: ['F', 'Gb', 'Ab', 'Bb', 'C', 'Db', 'Eb'],
      lydian: ['F', 'G', 'Ab', 'B', 'C', 'Db', 'Eb'],
      mixolydian: ['F', 'G', 'Ab', 'Bb', 'C', 'Db', 'Eb'],
      aeolian: ['F', 'G', 'Ab', 'Bb', 'C', 'Db', 'Eb'],
      locrian: ['F', 'Gb', 'Ab', 'Bb', 'Cb', 'Db', 'Eb'],
    },
    commonProgressions: [
      { name: 'i-iv-v', chords: ['Fm', 'Bbm', 'Cm'] },
      { name: 'i-VII-VI', chords: ['Fm', 'Eb', 'Db'] },
      { name: 'i-VI-iv-V', chords: ['Fm', 'Db', 'Bbm', 'C'] },
    ],
    enharmonic: null,
    color: keyColors['Ab'],
    position: calculatePosition(8, 12, 90),
    theoryNotes: {
      keyCharacteristics: 'Deep depression, funereal lament, groans of misery',
      famousWorks: ['Piano Concerto No. 2 - Chopin', 'Ballade No. 4 - Chopin'],
      relatedKeys: ['Ab', 'Cm', 'Bbm', 'Db', 'Eb'],
    },
  },
  Cm: {
    id: 'Cm',
    name: 'C minor',
    relativeMinor: 'Eb Major',
    keySignature: 3,
    sharpsOrFlats: 'flats',
    fifthClockwise: 'Gm',
    fifthCounterClockwise: 'Fm',
    primaryChords: ['Cm', 'Fm', 'Gm', 'G'],
    secondaryChords: ['Ddim', 'Eb', 'Ab', 'Bb'],
    scale: ['C', 'D', 'Eb', 'F', 'G', 'Ab', 'Bb'],
    modes: {
      ionian: ['C', 'D', 'Eb', 'F', 'G', 'Ab', 'Bb'],
      dorian: ['C', 'D', 'Eb', 'F', 'G', 'A', 'Bb'],
      phrygian: ['C', 'Db', 'Eb', 'F', 'G', 'Ab', 'Bb'],
      lydian: ['C', 'D', 'Eb', 'F#', 'G', 'Ab', 'Bb'],
      mixolydian: ['C', 'D', 'Eb', 'F', 'G', 'Ab', 'Bb'],
      aeolian: ['C', 'D', 'Eb', 'F', 'G', 'Ab', 'Bb'],
      locrian: ['C', 'Db', 'Eb', 'F', 'Gb', 'Ab', 'Bb'],
    },
    commonProgressions: [
      { name: 'i-iv-v', chords: ['Cm', 'Fm', 'Gm'] },
      { name: 'i-VII-VI', chords: ['Cm', 'Bb', 'Ab'] },
      { name: 'i-VI-VII-i', chords: ['Cm', 'Ab', 'Bb', 'Cm'] },
    ],
    enharmonic: null,
    color: keyColors['Eb'],
    position: calculatePosition(9, 12, 90),
    theoryNotes: {
      keyCharacteristics: 'Tragic, love-sick, longing',
      famousWorks: [
        'Symphony No. 5 - Beethoven',
        'Piano Concerto No. 24 - Mozart',
      ],
      relatedKeys: ['Eb', 'Gm', 'Fm', 'Ab', 'Bb'],
    },
  },
  Gm: {
    id: 'Gm',
    name: 'G minor',
    relativeMinor: 'Bb Major',
    keySignature: 2,
    sharpsOrFlats: 'flats',
    fifthClockwise: 'Dm',
    fifthCounterClockwise: 'Cm',
    primaryChords: ['Gm', 'Cm', 'Dm', 'D'],
    secondaryChords: ['Adim', 'Bb', 'Eb', 'F'],
    scale: ['G', 'A', 'Bb', 'C', 'D', 'Eb', 'F'],
    modes: {
      ionian: ['G', 'A', 'Bb', 'C', 'D', 'Eb', 'F'],
      dorian: ['G', 'A', 'Bb', 'C', 'D', 'E', 'F'],
      phrygian: ['G', 'Ab', 'Bb', 'C', 'D', 'Eb', 'F'],
      lydian: ['G', 'A', 'Bb', 'C#', 'D', 'Eb', 'F'],
      mixolydian: ['G', 'A', 'Bb', 'C', 'D', 'Eb', 'F'],
      aeolian: ['G', 'A', 'Bb', 'C', 'D', 'Eb', 'F'],
      locrian: ['G', 'Ab', 'Bb', 'C', 'Db', 'Eb', 'F'],
    },
    commonProgressions: [
      { name: 'i-iv-v', chords: ['Gm', 'Cm', 'Dm'] },
      { name: 'i-VII-VI', chords: ['Gm', 'F', 'Eb'] },
      { name: 'i-VI-VII-i', chords: ['Gm', 'Eb', 'F', 'Gm'] },
    ],
    enharmonic: null,
    color: keyColors['Bb'],
    position: calculatePosition(10, 12, 90),
    theoryNotes: {
      keyCharacteristics: 'Discontent, uneasiness, worry',
      famousWorks: ['Symphony No. 40 - Mozart', 'Symphony No. 25 - Mozart'],
      relatedKeys: ['Bb', 'Dm', 'Cm', 'Eb', 'F'],
    },
  },
  Dm: {
    id: 'Dm',
    name: 'D minor',
    relativeMinor: 'F Major',
    keySignature: 1,
    sharpsOrFlats: 'flats',
    fifthClockwise: 'Am',
    fifthCounterClockwise: 'Gm',
    primaryChords: ['Dm', 'Gm', 'Am', 'A'],
    secondaryChords: ['Edim', 'F', 'Bb', 'C'],
    scale: ['D', 'E', 'F', 'G', 'A', 'Bb', 'C'],
    modes: {
      ionian: ['D', 'E', 'F', 'G', 'A', 'Bb', 'C'],
      dorian: ['D', 'E', 'F', 'G', 'A', 'B', 'C'],
      phrygian: ['D', 'Eb', 'F', 'G', 'A', 'Bb', 'C'],
      lydian: ['D', 'E', 'F', 'G#', 'A', 'Bb', 'C'],
      mixolydian: ['D', 'E', 'F', 'G', 'A', 'Bb', 'C'],
      aeolian: ['D', 'E', 'F', 'G', 'A', 'Bb', 'C'],
      locrian: ['D', 'Eb', 'F', 'G', 'Ab', 'Bb', 'C'],
    },
    commonProgressions: [
      { name: 'i-iv-v', chords: ['Dm', 'Gm', 'Am'] },
      { name: 'i-VII-VI', chords: ['Dm', 'C', 'Bb'] },
      { name: 'i-VI-VII-i', chords: ['Dm', 'Bb', 'C', 'Dm'] },
    ],
    enharmonic: null,
    color: keyColors['F'],
    position: calculatePosition(11, 12, 90),
    theoryNotes: {
      keyCharacteristics: 'Serious, pious, ruminating',
      famousWorks: ['Requiem - Mozart', 'Art of Fugue - Bach'],
      relatedKeys: ['F', 'Am', 'Gm', 'Bb', 'C'],
    },
  },
}

export const getKeyData = (keyId: string): KeyInfo => {
  // Handle enharmonic equivalents for major keys
  if (keyId === 'F#/Gb' || keyId === 'F#' || keyId === 'Gb') {
    return keysData['F#'] // Return F# as default for enharmonic
  }

  // Handle enharmonic equivalents for minor keys
  if (keyId === 'D#m/Ebm' || keyId === 'D#m' || keyId === 'Ebm') {
    return keysData['D#m'] // Return D#m as default for enharmonic
  }

  return keysData[keyId] || keysData['C'] // Default to C if key not found
}

export const getAllKeys = (): KeyInfo[] => {
  return keyOrder.map(key => getKeyData(key))
}

export const getKeyOrder = (): string[] => {
  return keyOrder
}

export const getMinorKeyOrder = (): string[] => {
  return minorKeyOrder
}
