#!/usr/bin/env node

const fs = require('fs')
const path = require('path')
const chalk = require('chalk')

// Configuration
const LOCALES_DIR = path.join(__dirname, '..', 'src', 'locales')
const SUPPORTED_LANGUAGES = ['en', 'es', 'fr', 'de', 'zh-TW', 'zh-CN']
const NAMESPACES = [
  'common',
  'auth',
  'errors',
  'logbook',
  'reports',
  'scorebook',
  'toolbox',
]
const REFERENCE_LANGUAGE = 'en'
const NEEDS_TRANSLATION_PREFIX = '[NEEDS TRANSLATION] '

// Language names for better reporting
const LANGUAGE_NAMES = {
  en: 'English',
  es: 'Spanish',
  fr: 'French',
  de: 'German',
  'zh-TW': 'Traditional Chinese',
  'zh-CN': 'Simplified Chinese',
}

// Helper to load JSON file
function loadJsonFile(filePath) {
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'))
  } catch (error) {
    console.error(chalk.red(`Error loading ${filePath}:`), error.message)
    return null
  }
}

// Helper to save JSON file
function saveJsonFile(filePath, data) {
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n')
}

// Find all keys needing translation in an object
function findNeedsTranslation(obj, path = '') {
  const results = []

  for (const key in obj) {
    const fullPath = path ? `${path}.${key}` : key
    const value = obj[key]

    if (
      typeof value === 'string' &&
      value.startsWith(NEEDS_TRANSLATION_PREFIX)
    ) {
      results.push({
        path: fullPath,
        value: value.replace(NEEDS_TRANSLATION_PREFIX, ''),
        originalValue: value,
      })
    } else if (
      typeof value === 'object' &&
      value !== null &&
      !Array.isArray(value)
    ) {
      results.push(...findNeedsTranslation(value, fullPath))
    }
  }

  return results
}

// Get value by dot notation path
function getValueByPath(obj, path) {
  return path.split('.').reduce((acc, part) => acc && acc[part], obj)
}

// Set value by dot notation path
function setValueByPath(obj, path, value) {
  const parts = path.split('.')
  const last = parts.pop()
  const target = parts.reduce((acc, part) => {
    if (!acc[part]) acc[part] = {}
    return acc[part]
  }, obj)
  target[last] = value
}

// Generate translation suggestions based on patterns
function generateSuggestion(key, referenceValue, targetLang) {
  // Common UI patterns that can be auto-translated
  const patterns = {
    es: {
      Add: 'Añadir',
      Remove: 'Eliminar',
      Delete: 'Eliminar',
      Save: 'Guardar',
      Cancel: 'Cancelar',
      Close: 'Cerrar',
      Open: 'Abrir',
      Edit: 'Editar',
      Create: 'Crear',
      Update: 'Actualizar',
      Search: 'Buscar',
      Filter: 'Filtrar',
      Sort: 'Ordenar',
      Select: 'Seleccionar',
      Clear: 'Limpiar',
      Reset: 'Restablecer',
      Submit: 'Enviar',
      Confirm: 'Confirmar',
      Yes: 'Sí',
      No: 'No',
      OK: 'OK',
      Error: 'Error',
      Warning: 'Advertencia',
      Success: 'Éxito',
      Loading: 'Cargando',
      'Please wait': 'Por favor espere',
      Required: 'Requerido',
      Optional: 'Opcional',
      Settings: 'Configuración',
      Profile: 'Perfil',
      Logout: 'Cerrar sesión',
      Login: 'Iniciar sesión',
      'Sign in': 'Iniciar sesión',
      'Sign out': 'Cerrar sesión',
      Register: 'Registrarse',
      'Forgot password': 'Olvidé mi contraseña',
      'Reset password': 'Restablecer contraseña',
      'Change password': 'Cambiar contraseña',
      Email: 'Correo electrónico',
      Password: 'Contraseña',
      Username: 'Nombre de usuario',
      Name: 'Nombre',
      Description: 'Descripción',
      Title: 'Título',
      Date: 'Fecha',
      Time: 'Hora',
      Duration: 'Duración',
      Start: 'Iniciar',
      Stop: 'Detener',
      Pause: 'Pausar',
      Resume: 'Reanudar',
      Previous: 'Anterior',
      Next: 'Siguiente',
      Back: 'Atrás',
      Forward: 'Adelante',
      Home: 'Inicio',
      Dashboard: 'Panel',
      Overview: 'Resumen',
      Details: 'Detalles',
      Information: 'Información',
      Help: 'Ayuda',
      About: 'Acerca de',
      Contact: 'Contacto',
      Support: 'Soporte',
      Documentation: 'Documentación',
      Download: 'Descargar',
      Upload: 'Subir',
      Import: 'Importar',
      Export: 'Exportar',
      Print: 'Imprimir',
      Share: 'Compartir',
      Copy: 'Copiar',
      Paste: 'Pegar',
      Cut: 'Cortar',
      Undo: 'Deshacer',
      Redo: 'Rehacer',
      Refresh: 'Actualizar',
      Reload: 'Recargar',
      Retry: 'Reintentar',
      'Try again': 'Intentar de nuevo',
      View: 'Ver',
      Show: 'Mostrar',
      Hide: 'Ocultar',
      Expand: 'Expandir',
      Collapse: 'Contraer',
      More: 'Más',
      Less: 'Menos',
      All: 'Todo',
      None: 'Ninguno',
      Selected: 'Seleccionado',
      Unselected: 'No seleccionado',
      Active: 'Activo',
      Inactive: 'Inactivo',
      Enabled: 'Habilitado',
      Disabled: 'Deshabilitado',
      On: 'Encendido',
      Off: 'Apagado',
      Default: 'Predeterminado',
      Custom: 'Personalizado',
      Basic: 'Básico',
      Advanced: 'Avanzado',
      Simple: 'Simple',
      Complex: 'Complejo',
      Easy: 'Fácil',
      Hard: 'Difícil',
      New: 'Nuevo',
      Old: 'Antiguo',
      Recent: 'Reciente',
      Popular: 'Popular',
      Trending: 'Tendencia',
      Featured: 'Destacado',
      Recommended: 'Recomendado',
      Favorite: 'Favorito',
      Like: 'Me gusta',
      Dislike: 'No me gusta',
      Comment: 'Comentario',
      Reply: 'Responder',
      Follow: 'Seguir',
      Unfollow: 'Dejar de seguir',
      Block: 'Bloquear',
      Unblock: 'Desbloquear',
      Report: 'Reportar',
      Flag: 'Marcar',
      'Mark as read': 'Marcar como leído',
      'Mark as unread': 'Marcar como no leído',
      Archive: 'Archivar',
      Unarchive: 'Desarchivar',
      Trash: 'Papelera',
      Restore: 'Restaurar',
      'Permanently delete': 'Eliminar permanentemente',
      Move: 'Mover',
      Rename: 'Renombrar',
      Duplicate: 'Duplicar',
      Clone: 'Clonar',
      Merge: 'Fusionar',
      Split: 'Dividir',
      Join: 'Unir',
      Separate: 'Separar',
      Group: 'Agrupar',
      Ungroup: 'Desagrupar',
      Lock: 'Bloquear',
      Unlock: 'Desbloquear',
      Pin: 'Fijar',
      Unpin: 'Desfijar',
      Bookmark: 'Marcador',
      Tag: 'Etiqueta',
      Label: 'Etiqueta',
      Category: 'Categoría',
      Type: 'Tipo',
      Status: 'Estado',
      Priority: 'Prioridad',
      High: 'Alta',
      Medium: 'Media',
      Low: 'Baja',
      Urgent: 'Urgente',
      Important: 'Importante',
      Normal: 'Normal',
      Minor: 'Menor',
      Major: 'Mayor',
      Critical: 'Crítico',
      Public: 'Público',
      Private: 'Privado',
      Draft: 'Borrador',
      Published: 'Publicado',
      Pending: 'Pendiente',
      Approved: 'Aprobado',
      Rejected: 'Rechazado',
      Completed: 'Completado',
      'In progress': 'En progreso',
      'Not started': 'No iniciado',
      Cancelled: 'Cancelado',
      Postponed: 'Pospuesto',
      Scheduled: 'Programado',
      Overdue: 'Vencido',
      Today: 'Hoy',
      Yesterday: 'Ayer',
      Tomorrow: 'Mañana',
      'This week': 'Esta semana',
      'Last week': 'Semana pasada',
      'Next week': 'Próxima semana',
      'This month': 'Este mes',
      'Last month': 'Mes pasado',
      'Next month': 'Próximo mes',
      'This year': 'Este año',
      'Last year': 'Año pasado',
      'Next year': 'Próximo año',
      Monday: 'Lunes',
      Tuesday: 'Martes',
      Wednesday: 'Miércoles',
      Thursday: 'Jueves',
      Friday: 'Viernes',
      Saturday: 'Sábado',
      Sunday: 'Domingo',
      January: 'Enero',
      February: 'Febrero',
      March: 'Marzo',
      April: 'Abril',
      May: 'Mayo',
      June: 'Junio',
      July: 'Julio',
      August: 'Agosto',
      September: 'Septiembre',
      October: 'Octubre',
      November: 'Noviembre',
      December: 'Diciembre',
    },
    fr: {
      Add: 'Ajouter',
      Remove: 'Supprimer',
      Delete: 'Supprimer',
      Save: 'Enregistrer',
      Cancel: 'Annuler',
      Close: 'Fermer',
      Open: 'Ouvrir',
      Edit: 'Modifier',
      Create: 'Créer',
      Update: 'Mettre à jour',
      Search: 'Rechercher',
      Filter: 'Filtrer',
      Sort: 'Trier',
      Select: 'Sélectionner',
      Clear: 'Effacer',
      Reset: 'Réinitialiser',
      Submit: 'Soumettre',
      Confirm: 'Confirmer',
      Yes: 'Oui',
      No: 'Non',
      OK: 'OK',
      Error: 'Erreur',
      Warning: 'Avertissement',
      Success: 'Succès',
      Loading: 'Chargement',
      'Please wait': 'Veuillez patienter',
      Required: 'Requis',
      Optional: 'Optionnel',
      Settings: 'Paramètres',
      Profile: 'Profil',
      Logout: 'Déconnexion',
      Login: 'Connexion',
      'Sign in': 'Se connecter',
      'Sign out': 'Se déconnecter',
      Register: "S'inscrire",
      'Forgot password': 'Mot de passe oublié',
      'Reset password': 'Réinitialiser le mot de passe',
      'Change password': 'Changer le mot de passe',
      Email: 'E-mail',
      Password: 'Mot de passe',
      Username: "Nom d'utilisateur",
      Name: 'Nom',
      Description: 'Description',
      Title: 'Titre',
      Date: 'Date',
      Time: 'Heure',
      Duration: 'Durée',
      Start: 'Démarrer',
      Stop: 'Arrêter',
      Pause: 'Pause',
      Resume: 'Reprendre',
      Previous: 'Précédent',
      Next: 'Suivant',
      Back: 'Retour',
      Forward: 'Avancer',
      Home: 'Accueil',
      Dashboard: 'Tableau de bord',
      Overview: "Vue d'ensemble",
      Details: 'Détails',
      Information: 'Information',
      Help: 'Aide',
      About: 'À propos',
      Contact: 'Contact',
      Support: 'Support',
      Documentation: 'Documentation',
      Download: 'Télécharger',
      Upload: 'Téléverser',
      Import: 'Importer',
      Export: 'Exporter',
      Print: 'Imprimer',
      Share: 'Partager',
      Copy: 'Copier',
      Paste: 'Coller',
      Cut: 'Couper',
      Undo: 'Annuler',
      Redo: 'Rétablir',
      Refresh: 'Actualiser',
      Reload: 'Recharger',
      Retry: 'Réessayer',
      'Try again': 'Réessayer',
      View: 'Voir',
      Show: 'Afficher',
      Hide: 'Masquer',
      Expand: 'Développer',
      Collapse: 'Réduire',
      More: 'Plus',
      Less: 'Moins',
      All: 'Tout',
      None: 'Aucun',
      Selected: 'Sélectionné',
      Unselected: 'Non sélectionné',
      Active: 'Actif',
      Inactive: 'Inactif',
      Enabled: 'Activé',
      Disabled: 'Désactivé',
      On: 'Activé',
      Off: 'Désactivé',
      Default: 'Par défaut',
      Custom: 'Personnalisé',
      Basic: 'Basique',
      Advanced: 'Avancé',
      Simple: 'Simple',
      Complex: 'Complexe',
      Easy: 'Facile',
      Hard: 'Difficile',
      New: 'Nouveau',
      Old: 'Ancien',
      Recent: 'Récent',
      Popular: 'Populaire',
      Trending: 'Tendance',
      Featured: 'En vedette',
      Recommended: 'Recommandé',
      Favorite: 'Favori',
      Like: 'Aimer',
      Dislike: 'Ne pas aimer',
      Comment: 'Commentaire',
      Reply: 'Répondre',
      Follow: 'Suivre',
      Unfollow: 'Ne plus suivre',
      Block: 'Bloquer',
      Unblock: 'Débloquer',
      Report: 'Signaler',
      Flag: 'Signaler',
      'Mark as read': 'Marquer comme lu',
      'Mark as unread': 'Marquer comme non lu',
      Archive: 'Archiver',
      Unarchive: 'Désarchiver',
      Trash: 'Corbeille',
      Restore: 'Restaurer',
      'Permanently delete': 'Supprimer définitivement',
      Move: 'Déplacer',
      Rename: 'Renommer',
      Duplicate: 'Dupliquer',
      Clone: 'Cloner',
      Merge: 'Fusionner',
      Split: 'Diviser',
      Join: 'Joindre',
      Separate: 'Séparer',
      Group: 'Grouper',
      Ungroup: 'Dégrouper',
      Lock: 'Verrouiller',
      Unlock: 'Déverrouiller',
      Pin: 'Épingler',
      Unpin: 'Désépingler',
      Bookmark: 'Marque-page',
      Tag: 'Étiquette',
      Label: 'Libellé',
      Category: 'Catégorie',
      Type: 'Type',
      Status: 'Statut',
      Priority: 'Priorité',
      High: 'Élevée',
      Medium: 'Moyenne',
      Low: 'Faible',
      Urgent: 'Urgent',
      Important: 'Important',
      Normal: 'Normal',
      Minor: 'Mineur',
      Major: 'Majeur',
      Critical: 'Critique',
      Public: 'Public',
      Private: 'Privé',
      Draft: 'Brouillon',
      Published: 'Publié',
      Pending: 'En attente',
      Approved: 'Approuvé',
      Rejected: 'Rejeté',
      Completed: 'Terminé',
      'In progress': 'En cours',
      'Not started': 'Non commencé',
      Cancelled: 'Annulé',
      Postponed: 'Reporté',
      Scheduled: 'Planifié',
      Overdue: 'En retard',
      Today: "Aujourd'hui",
      Yesterday: 'Hier',
      Tomorrow: 'Demain',
      'This week': 'Cette semaine',
      'Last week': 'Semaine dernière',
      'Next week': 'Semaine prochaine',
      'This month': 'Ce mois',
      'Last month': 'Mois dernier',
      'Next month': 'Mois prochain',
      'This year': 'Cette année',
      'Last year': 'Année dernière',
      'Next year': 'Année prochaine',
      Monday: 'Lundi',
      Tuesday: 'Mardi',
      Wednesday: 'Mercredi',
      Thursday: 'Jeudi',
      Friday: 'Vendredi',
      Saturday: 'Samedi',
      Sunday: 'Dimanche',
      January: 'Janvier',
      February: 'Février',
      March: 'Mars',
      April: 'Avril',
      May: 'Mai',
      June: 'Juin',
      July: 'Juillet',
      August: 'Août',
      September: 'Septembre',
      October: 'Octobre',
      November: 'Novembre',
      December: 'Décembre',
    },
    de: {
      Add: 'Hinzufügen',
      Remove: 'Entfernen',
      Delete: 'Löschen',
      Save: 'Speichern',
      Cancel: 'Abbrechen',
      Close: 'Schließen',
      Open: 'Öffnen',
      Edit: 'Bearbeiten',
      Create: 'Erstellen',
      Update: 'Aktualisieren',
      Search: 'Suchen',
      Filter: 'Filtern',
      Sort: 'Sortieren',
      Select: 'Auswählen',
      Clear: 'Löschen',
      Reset: 'Zurücksetzen',
      Submit: 'Absenden',
      Confirm: 'Bestätigen',
      Yes: 'Ja',
      No: 'Nein',
      OK: 'OK',
      Error: 'Fehler',
      Warning: 'Warnung',
      Success: 'Erfolg',
      Loading: 'Laden',
      'Please wait': 'Bitte warten',
      Required: 'Erforderlich',
      Optional: 'Optional',
      Settings: 'Einstellungen',
      Profile: 'Profil',
      Logout: 'Abmelden',
      Login: 'Anmelden',
      'Sign in': 'Anmelden',
      'Sign out': 'Abmelden',
      Register: 'Registrieren',
      'Forgot password': 'Passwort vergessen',
      'Reset password': 'Passwort zurücksetzen',
      'Change password': 'Passwort ändern',
      Email: 'E-Mail',
      Password: 'Passwort',
      Username: 'Benutzername',
      Name: 'Name',
      Description: 'Beschreibung',
      Title: 'Titel',
      Date: 'Datum',
      Time: 'Zeit',
      Duration: 'Dauer',
      Start: 'Starten',
      Stop: 'Stoppen',
      Pause: 'Pause',
      Resume: 'Fortsetzen',
      Previous: 'Vorherige',
      Next: 'Nächste',
      Back: 'Zurück',
      Forward: 'Vorwärts',
      Home: 'Startseite',
      Dashboard: 'Dashboard',
      Overview: 'Übersicht',
      Details: 'Details',
      Information: 'Information',
      Help: 'Hilfe',
      About: 'Über',
      Contact: 'Kontakt',
      Support: 'Unterstützung',
      Documentation: 'Dokumentation',
      Download: 'Herunterladen',
      Upload: 'Hochladen',
      Import: 'Importieren',
      Export: 'Exportieren',
      Print: 'Drucken',
      Share: 'Teilen',
      Copy: 'Kopieren',
      Paste: 'Einfügen',
      Cut: 'Ausschneiden',
      Undo: 'Rückgängig',
      Redo: 'Wiederholen',
      Refresh: 'Aktualisieren',
      Reload: 'Neu laden',
      Retry: 'Wiederholen',
      'Try again': 'Erneut versuchen',
      View: 'Ansehen',
      Show: 'Anzeigen',
      Hide: 'Ausblenden',
      Expand: 'Erweitern',
      Collapse: 'Reduzieren',
      More: 'Mehr',
      Less: 'Weniger',
      All: 'Alle',
      None: 'Keine',
      Selected: 'Ausgewählt',
      Unselected: 'Nicht ausgewählt',
      Active: 'Aktiv',
      Inactive: 'Inaktiv',
      Enabled: 'Aktiviert',
      Disabled: 'Deaktiviert',
      On: 'Ein',
      Off: 'Aus',
      Default: 'Standard',
      Custom: 'Benutzerdefiniert',
      Basic: 'Basis',
      Advanced: 'Erweitert',
      Simple: 'Einfach',
      Complex: 'Komplex',
      Easy: 'Einfach',
      Hard: 'Schwer',
      New: 'Neu',
      Old: 'Alt',
      Recent: 'Kürzlich',
      Popular: 'Beliebt',
      Trending: 'Trend',
      Featured: 'Vorgestellt',
      Recommended: 'Empfohlen',
      Favorite: 'Favorit',
      Like: 'Gefällt mir',
      Dislike: 'Gefällt mir nicht',
      Comment: 'Kommentar',
      Reply: 'Antworten',
      Follow: 'Folgen',
      Unfollow: 'Entfolgen',
      Block: 'Blockieren',
      Unblock: 'Blockierung aufheben',
      Report: 'Melden',
      Flag: 'Markieren',
      'Mark as read': 'Als gelesen markieren',
      'Mark as unread': 'Als ungelesen markieren',
      Archive: 'Archivieren',
      Unarchive: 'Aus Archiv entfernen',
      Trash: 'Papierkorb',
      Restore: 'Wiederherstellen',
      'Permanently delete': 'Dauerhaft löschen',
      Move: 'Verschieben',
      Rename: 'Umbenennen',
      Duplicate: 'Duplizieren',
      Clone: 'Klonen',
      Merge: 'Zusammenführen',
      Split: 'Teilen',
      Join: 'Verbinden',
      Separate: 'Trennen',
      Group: 'Gruppieren',
      Ungroup: 'Gruppierung aufheben',
      Lock: 'Sperren',
      Unlock: 'Entsperren',
      Pin: 'Anheften',
      Unpin: 'Loslösen',
      Bookmark: 'Lesezeichen',
      Tag: 'Tag',
      Label: 'Bezeichnung',
      Category: 'Kategorie',
      Type: 'Typ',
      Status: 'Status',
      Priority: 'Priorität',
      High: 'Hoch',
      Medium: 'Mittel',
      Low: 'Niedrig',
      Urgent: 'Dringend',
      Important: 'Wichtig',
      Normal: 'Normal',
      Minor: 'Gering',
      Major: 'Groß',
      Critical: 'Kritisch',
      Public: 'Öffentlich',
      Private: 'Privat',
      Draft: 'Entwurf',
      Published: 'Veröffentlicht',
      Pending: 'Ausstehend',
      Approved: 'Genehmigt',
      Rejected: 'Abgelehnt',
      Completed: 'Abgeschlossen',
      'In progress': 'In Bearbeitung',
      'Not started': 'Nicht gestartet',
      Cancelled: 'Abgebrochen',
      Postponed: 'Verschoben',
      Scheduled: 'Geplant',
      Overdue: 'Überfällig',
      Today: 'Heute',
      Yesterday: 'Gestern',
      Tomorrow: 'Morgen',
      'This week': 'Diese Woche',
      'Last week': 'Letzte Woche',
      'Next week': 'Nächste Woche',
      'This month': 'Diesen Monat',
      'Last month': 'Letzten Monat',
      'Next month': 'Nächsten Monat',
      'This year': 'Dieses Jahr',
      'Last year': 'Letztes Jahr',
      'Next year': 'Nächstes Jahr',
      Monday: 'Montag',
      Tuesday: 'Dienstag',
      Wednesday: 'Mittwoch',
      Thursday: 'Donnerstag',
      Friday: 'Freitag',
      Saturday: 'Samstag',
      Sunday: 'Sonntag',
      January: 'Januar',
      February: 'Februar',
      March: 'März',
      April: 'April',
      May: 'Mai',
      June: 'Juni',
      July: 'Juli',
      August: 'August',
      September: 'September',
      October: 'Oktober',
      November: 'November',
      December: 'Dezember',
    },
    'zh-TW': {
      Add: '新增',
      Remove: '移除',
      Delete: '刪除',
      Save: '儲存',
      Cancel: '取消',
      Close: '關閉',
      Open: '開啟',
      Edit: '編輯',
      Create: '建立',
      Update: '更新',
      Search: '搜尋',
      Filter: '篩選',
      Sort: '排序',
      Select: '選擇',
      Clear: '清除',
      Reset: '重設',
      Submit: '提交',
      Confirm: '確認',
      Yes: '是',
      No: '否',
      OK: '確定',
      Error: '錯誤',
      Warning: '警告',
      Success: '成功',
      Loading: '載入中',
      'Please wait': '請稍候',
      Required: '必填',
      Optional: '選填',
      Settings: '設定',
      Profile: '個人資料',
      Logout: '登出',
      Login: '登入',
      'Sign in': '登入',
      'Sign out': '登出',
      Register: '註冊',
      'Forgot password': '忘記密碼',
      'Reset password': '重設密碼',
      'Change password': '變更密碼',
      Email: '電子郵件',
      Password: '密碼',
      Username: '使用者名稱',
      Name: '名稱',
      Description: '描述',
      Title: '標題',
      Date: '日期',
      Time: '時間',
      Duration: '持續時間',
      Start: '開始',
      Stop: '停止',
      Pause: '暫停',
      Resume: '繼續',
      Previous: '上一個',
      Next: '下一個',
      Back: '返回',
      Forward: '前進',
      Home: '首頁',
      Dashboard: '儀表板',
      Overview: '總覽',
      Details: '詳細資料',
      Information: '資訊',
      Help: '說明',
      About: '關於',
      Contact: '聯絡',
      Support: '支援',
      Documentation: '文件',
      Download: '下載',
      Upload: '上傳',
      Import: '匯入',
      Export: '匯出',
      Print: '列印',
      Share: '分享',
      Copy: '複製',
      Paste: '貼上',
      Cut: '剪下',
      Undo: '復原',
      Redo: '重做',
      Refresh: '重新整理',
      Reload: '重新載入',
      Retry: '重試',
      'Try again': '再試一次',
      View: '檢視',
      Show: '顯示',
      Hide: '隱藏',
      Expand: '展開',
      Collapse: '收合',
      More: '更多',
      Less: '更少',
      All: '全部',
      None: '無',
      Selected: '已選擇',
      Unselected: '未選擇',
      Active: '啟用',
      Inactive: '停用',
      Enabled: '已啟用',
      Disabled: '已停用',
      On: '開',
      Off: '關',
      Default: '預設',
      Custom: '自訂',
      Basic: '基本',
      Advanced: '進階',
      Simple: '簡單',
      Complex: '複雜',
      Easy: '簡單',
      Hard: '困難',
      New: '新增',
      Old: '舊的',
      Recent: '最近',
      Popular: '熱門',
      Trending: '趨勢',
      Featured: '精選',
      Recommended: '推薦',
      Favorite: '最愛',
      Like: '喜歡',
      Dislike: '不喜歡',
      Comment: '評論',
      Reply: '回覆',
      Follow: '追蹤',
      Unfollow: '取消追蹤',
      Block: '封鎖',
      Unblock: '解除封鎖',
      Report: '檢舉',
      Flag: '標記',
      'Mark as read': '標記為已讀',
      'Mark as unread': '標記為未讀',
      Archive: '封存',
      Unarchive: '取消封存',
      Trash: '垃圾桶',
      Restore: '還原',
      'Permanently delete': '永久刪除',
      Move: '移動',
      Rename: '重新命名',
      Duplicate: '複製',
      Clone: '複製',
      Merge: '合併',
      Split: '分割',
      Join: '加入',
      Separate: '分離',
      Group: '群組',
      Ungroup: '取消群組',
      Lock: '鎖定',
      Unlock: '解鎖',
      Pin: '釘選',
      Unpin: '取消釘選',
      Bookmark: '書籤',
      Tag: '標籤',
      Label: '標籤',
      Category: '類別',
      Type: '類型',
      Status: '狀態',
      Priority: '優先順序',
      High: '高',
      Medium: '中',
      Low: '低',
      Urgent: '緊急',
      Important: '重要',
      Normal: '一般',
      Minor: '次要',
      Major: '主要',
      Critical: '關鍵',
      Public: '公開',
      Private: '私人',
      Draft: '草稿',
      Published: '已發布',
      Pending: '待處理',
      Approved: '已核准',
      Rejected: '已拒絕',
      Completed: '已完成',
      'In progress': '進行中',
      'Not started': '未開始',
      Cancelled: '已取消',
      Postponed: '已延後',
      Scheduled: '已排程',
      Overdue: '逾期',
      Today: '今天',
      Yesterday: '昨天',
      Tomorrow: '明天',
      'This week': '本週',
      'Last week': '上週',
      'Next week': '下週',
      'This month': '本月',
      'Last month': '上個月',
      'Next month': '下個月',
      'This year': '今年',
      'Last year': '去年',
      'Next year': '明年',
      Monday: '星期一',
      Tuesday: '星期二',
      Wednesday: '星期三',
      Thursday: '星期四',
      Friday: '星期五',
      Saturday: '星期六',
      Sunday: '星期日',
      January: '一月',
      February: '二月',
      March: '三月',
      April: '四月',
      May: '五月',
      June: '六月',
      July: '七月',
      August: '八月',
      September: '九月',
      October: '十月',
      November: '十一月',
      December: '十二月',
    },
    'zh-CN': {
      Add: '添加',
      Remove: '移除',
      Delete: '删除',
      Save: '保存',
      Cancel: '取消',
      Close: '关闭',
      Open: '打开',
      Edit: '编辑',
      Create: '创建',
      Update: '更新',
      Search: '搜索',
      Filter: '筛选',
      Sort: '排序',
      Select: '选择',
      Clear: '清除',
      Reset: '重置',
      Submit: '提交',
      Confirm: '确认',
      Yes: '是',
      No: '否',
      OK: '确定',
      Error: '错误',
      Warning: '警告',
      Success: '成功',
      Loading: '加载中',
      'Please wait': '请稍候',
      Required: '必填',
      Optional: '选填',
      Settings: '设置',
      Profile: '个人资料',
      Logout: '退出',
      Login: '登录',
      'Sign in': '登录',
      'Sign out': '退出',
      Register: '注册',
      'Forgot password': '忘记密码',
      'Reset password': '重置密码',
      'Change password': '更改密码',
      Email: '电子邮件',
      Password: '密码',
      Username: '用户名',
      Name: '名称',
      Description: '描述',
      Title: '标题',
      Date: '日期',
      Time: '时间',
      Duration: '时长',
      Start: '开始',
      Stop: '停止',
      Pause: '暂停',
      Resume: '继续',
      Previous: '上一个',
      Next: '下一个',
      Back: '返回',
      Forward: '前进',
      Home: '首页',
      Dashboard: '仪表盘',
      Overview: '概览',
      Details: '详情',
      Information: '信息',
      Help: '帮助',
      About: '关于',
      Contact: '联系',
      Support: '支持',
      Documentation: '文档',
      Download: '下载',
      Upload: '上传',
      Import: '导入',
      Export: '导出',
      Print: '打印',
      Share: '分享',
      Copy: '复制',
      Paste: '粘贴',
      Cut: '剪切',
      Undo: '撤销',
      Redo: '重做',
      Refresh: '刷新',
      Reload: '重新加载',
      Retry: '重试',
      'Try again': '再试一次',
      View: '查看',
      Show: '显示',
      Hide: '隐藏',
      Expand: '展开',
      Collapse: '收起',
      More: '更多',
      Less: '更少',
      All: '全部',
      None: '无',
      Selected: '已选择',
      Unselected: '未选择',
      Active: '活动',
      Inactive: '非活动',
      Enabled: '已启用',
      Disabled: '已禁用',
      On: '开',
      Off: '关',
      Default: '默认',
      Custom: '自定义',
      Basic: '基本',
      Advanced: '高级',
      Simple: '简单',
      Complex: '复杂',
      Easy: '容易',
      Hard: '困难',
      New: '新建',
      Old: '旧的',
      Recent: '最近',
      Popular: '热门',
      Trending: '趋势',
      Featured: '精选',
      Recommended: '推荐',
      Favorite: '收藏',
      Like: '喜欢',
      Dislike: '不喜欢',
      Comment: '评论',
      Reply: '回复',
      Follow: '关注',
      Unfollow: '取消关注',
      Block: '屏蔽',
      Unblock: '解除屏蔽',
      Report: '举报',
      Flag: '标记',
      'Mark as read': '标记为已读',
      'Mark as unread': '标记为未读',
      Archive: '归档',
      Unarchive: '取消归档',
      Trash: '回收站',
      Restore: '恢复',
      'Permanently delete': '永久删除',
      Move: '移动',
      Rename: '重命名',
      Duplicate: '复制',
      Clone: '克隆',
      Merge: '合并',
      Split: '拆分',
      Join: '加入',
      Separate: '分离',
      Group: '分组',
      Ungroup: '取消分组',
      Lock: '锁定',
      Unlock: '解锁',
      Pin: '固定',
      Unpin: '取消固定',
      Bookmark: '书签',
      Tag: '标签',
      Label: '标签',
      Category: '类别',
      Type: '类型',
      Status: '状态',
      Priority: '优先级',
      High: '高',
      Medium: '中',
      Low: '低',
      Urgent: '紧急',
      Important: '重要',
      Normal: '正常',
      Minor: '次要',
      Major: '主要',
      Critical: '关键',
      Public: '公开',
      Private: '私密',
      Draft: '草稿',
      Published: '已发布',
      Pending: '待处理',
      Approved: '已批准',
      Rejected: '已拒绝',
      Completed: '已完成',
      'In progress': '进行中',
      'Not started': '未开始',
      Cancelled: '已取消',
      Postponed: '已推迟',
      Scheduled: '已计划',
      Overdue: '逾期',
      Today: '今天',
      Yesterday: '昨天',
      Tomorrow: '明天',
      'This week': '本周',
      'Last week': '上周',
      'Next week': '下周',
      'This month': '本月',
      'Last month': '上个月',
      'Next month': '下个月',
      'This year': '今年',
      'Last year': '去年',
      'Next year': '明年',
      Monday: '星期一',
      Tuesday: '星期二',
      Wednesday: '星期三',
      Thursday: '星期四',
      Friday: '星期五',
      Saturday: '星期六',
      Sunday: '星期日',
      January: '一月',
      February: '二月',
      March: '三月',
      April: '四月',
      May: '五月',
      June: '六月',
      July: '七月',
      August: '八月',
      September: '九月',
      October: '十月',
      November: '十一月',
      December: '十二月',
    },
  }

  // Try exact match first
  if (patterns[targetLang] && patterns[targetLang][referenceValue]) {
    return patterns[targetLang][referenceValue]
  }

  // Try case-insensitive match
  const lowerRef = referenceValue.toLowerCase()
  for (const [key, value] of Object.entries(patterns[targetLang] || {})) {
    if (key.toLowerCase() === lowerRef) {
      return value
    }
  }

  return null
}

// Process a single namespace/language
function processTranslations(namespace, lang, options = {}) {
  const langPath = path.join(LOCALES_DIR, lang, `${namespace}.json`)
  const langData = loadJsonFile(langPath)

  if (!langData) {
    console.error(chalk.red(`Could not load ${lang} file for ${namespace}`))
    return 0
  }

  // Load reference data for suggestions
  const referencePath = path.join(
    LOCALES_DIR,
    REFERENCE_LANGUAGE,
    `${namespace}.json`
  )
  const referenceData = loadJsonFile(referencePath)

  const needsTranslation = findNeedsTranslation(langData)

  if (needsTranslation.length === 0) {
    return 0
  }

  let updated = 0

  needsTranslation.forEach(({ path: keyPath, value }) => {
    // Get reference value for context
    const referenceValue = referenceData
      ? getValueByPath(referenceData, keyPath)
      : null

    // Try to generate a suggestion
    const suggestion = generateSuggestion(keyPath, referenceValue, lang)

    if (suggestion && options.autoTranslate) {
      setValueByPath(langData, keyPath, suggestion)
      console.log(
        chalk.green(`  ✓ Auto-translated: ${keyPath} → "${suggestion}"`)
      )
      updated++
    } else if (options.showSuggestions && suggestion) {
      console.log(
        chalk.yellow(`  ? ${keyPath}: "${value}" → Suggestion: "${suggestion}"`)
      )
    } else if (options.verbose) {
      console.log(chalk.gray(`  - ${keyPath}: "${value}"`))
    }
  })

  if (updated > 0 && !options.dryRun) {
    saveJsonFile(langPath, langData)
  }

  return updated
}

// Main function
function main() {
  const args = process.argv.slice(2)
  const options = {
    autoTranslate: args.includes('--auto'),
    showSuggestions: args.includes('--suggest'),
    verbose: args.includes('--verbose'),
    dryRun: args.includes('--dry-run'),
    namespace: null,
    language: null,
  }

  // Parse namespace and language options
  const namespaceIndex = args.findIndex(arg => arg === '--namespace')
  if (namespaceIndex !== -1 && args[namespaceIndex + 1]) {
    options.namespace = args[namespaceIndex + 1]
  }

  const languageIndex = args.findIndex(arg => arg === '--language')
  if (languageIndex !== -1 && args[languageIndex + 1]) {
    options.language = args[languageIndex + 1]
  }

  console.log(chalk.bold.cyan('🌐 Translation Helper Tool'))
  console.log(chalk.gray('Finding and helping with missing translations\n'))

  if (options.dryRun) {
    console.log(chalk.yellow('🔍 DRY RUN MODE - No files will be modified\n'))
  }

  let totalNeedsTranslation = 0
  let totalAutoTranslated = 0

  // Process specified namespace/language or all
  const namespacesToProcess = options.namespace
    ? [options.namespace]
    : NAMESPACES
  const languagesToProcess = options.language
    ? [options.language]
    : SUPPORTED_LANGUAGES.filter(l => l !== REFERENCE_LANGUAGE)

  namespacesToProcess.forEach(namespace => {
    console.log(chalk.blue(`\nNamespace: ${namespace}`))

    languagesToProcess.forEach(lang => {
      const langPath = path.join(LOCALES_DIR, lang, `${namespace}.json`)
      const langData = loadJsonFile(langPath)

      if (!langData) {
        return
      }

      const needsTranslation = findNeedsTranslation(langData)
      totalNeedsTranslation += needsTranslation.length

      if (needsTranslation.length > 0) {
        console.log(
          chalk.cyan(
            `\n${LANGUAGE_NAMES[lang]} (${lang}): ${needsTranslation.length} translations needed`
          )
        )

        const updated = processTranslations(namespace, lang, options)
        totalAutoTranslated += updated
      }
    })
  })

  // Summary
  console.log(chalk.gray('\n' + '='.repeat(60)))
  console.log(chalk.bold('\n📊 Summary:'))
  console.log(`Total translations needed: ${totalNeedsTranslation}`)

  if (options.autoTranslate) {
    console.log(chalk.green(`Auto-translated: ${totalAutoTranslated}`))
    console.log(
      chalk.yellow(
        `Still needs manual translation: ${totalNeedsTranslation - totalAutoTranslated}`
      )
    )
  }

  // Help text
  if (!options.autoTranslate && !options.showSuggestions) {
    console.log(chalk.gray('\nOptions:'))
    console.log(chalk.gray('  --auto          Auto-translate common UI terms'))
    console.log(chalk.gray('  --suggest       Show translation suggestions'))
    console.log(
      chalk.gray('  --verbose       Show all keys needing translation')
    )
    console.log(chalk.gray('  --dry-run       Preview changes without saving'))
    console.log(chalk.gray('  --namespace <n> Process specific namespace only'))
    console.log(chalk.gray('  --language <l>  Process specific language only'))
    console.log(
      chalk.gray('\nExample: npm run translate:missing -- --auto --suggest')
    )
  }
}

// Run the script
main()
